// ─────────────────────────────────────────────────────────────────────────────
// Aquatic Plants & Algae Templates
// Maps to Universal Template T9 — Aquatic Plant / Biomass
// Covers: Seaweed Farming, Spirulina / Microalgae
// ─────────────────────────────────────────────────────────────────────────────
import type { ProductionTemplate } from '../types';

// ─── SEAWEED FARMING ─────────────────────────────────────────────────────────
export const seaweedTemplate: ProductionTemplate = {
  id: 'seaweed-farming',
  name: 'Seaweed Farming',
  shortName: 'Seaweed',
  category: 'aquatic_plants',
  species: 'Kappaphycus alvarezii / Gracilaria spp.',
  purpose: 'Food, Agar, Carrageenan & Biofertiliser',
  description:
    'Marine seaweed cultivation on longlines or nets. Short cycle (45–60 days). Outputs: fresh/dried seaweed for food, agar, carrageenan, or biofertiliser.',
  icon: '🌿',
  color: '#065f46',
  tags: ['seaweed', 'macroalgae', 'Kappaphycus', 'Gracilaria', 'carrageenan', 'agar', 'marine'],
  materials: [
    { id: 'seed-thalli', name: 'Seed Thalli (vegetative propagules)', unit: 'kg', category: 'input' },
    { id: 'longlines', name: 'Longlines / Nets / Ropes', unit: 'count', category: 'input' },
    { id: 'fresh-seaweed', name: 'Fresh Seaweed', unit: 'kg', category: 'output' },
    { id: 'dried-seaweed', name: 'Dried Seaweed', unit: 'kg', category: 'output' },
    { id: 'seaweed-meal', name: 'Seaweed Meal / Powder', unit: 'kg', category: 'output' },
    { id: 'seaweed-extract', name: 'Liquid Seaweed Biofertiliser', unit: 'litre', category: 'output' },
  ],
  kpis: [
    { id: 'sdr', name: 'Specific Daily Growth Rate (%/day)', unit: 'percent', goodDirection: 'up', benchmark: 3 },
    { id: 'fresh-yield', name: 'Fresh Yield per Hectare per Cycle', unit: 'tonne', goodDirection: 'up', benchmark: 15 },
    { id: 'dry-ratio', name: 'Fresh-to-Dry Ratio', unit: 'ratio', goodDirection: 'neutral', benchmark: 7 },
    { id: 'cycle-days', name: 'Cycle Duration', unit: 'day', goodDirection: 'neutral', benchmark: 45 },
  ],
  stages: [
    {
      id: 'site-prep',
      name: 'Site Selection & Infrastructure Setup',
      typicalDurationDays: 14,
      color: '#d1fae5',
      inputs: [
        { id: 'stakes', label: 'Bamboo Stakes / Anchor Poles', unit: 'count', required: true },
        { id: 'ropes', label: 'Longlines / PE Ropes', unit: 'count', required: true },
        { id: 'buoys', label: 'Floats / Buoys', unit: 'count', required: false },
      ],
      activities: [
        'Select site: clear water, 1–3 m depth at low tide, good water flow',
        'Avoid freshwater runoff, sediment-heavy areas',
        'Set up longlines parallel to current direction',
        'Space lines 1 m apart, main lines 5–10 m long',
        'Secure anchors and test for drift',
        'Record GPS coordinates of farm blocks',
      ],
      measurements: [
        { id: 'salinity', name: 'Salinity', unit: 'percent', frequency: 'weekly', required: true, benchmark: { min: 28, max: 35 } },
        { id: 'temp-water', name: 'Water Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 25, max: 30 } },
        { id: 'water-clarity', name: 'Water Clarity (Secchi depth, m)', unit: 'g', frequency: 'weekly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['seeding'],
    },
    {
      id: 'seeding',
      name: 'Seeding (Vegetative Propagation)',
      typicalDurationDays: 3,
      color: '#6ee7b7',
      inputs: [
        { id: 'thalli', label: 'Healthy Seed Thalli (actively growing tips)', unit: 'kg', required: true },
        { id: 'tie-strips', label: 'Tie Strips / Rubber Bands', unit: 'count', required: true },
      ],
      activities: [
        'Select vigorous, disease-free thalli weighing 50–100 g per seed',
        'Tie seed portions to longlines every 20–25 cm',
        'Submerge lines at 20–30 cm depth below surface',
        'Record seeding density: target 50–100 g/m of line',
        'Inspect farm 48h after seeding for detachment',
      ],
      measurements: [
        { id: 'seed-weight', name: 'Initial Seed Weight', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'seed-density', name: 'Seeds per Metre of Rope', unit: 'count', frequency: 'per_event', required: true, benchmark: { target: 4 } },
      ],
      outputs: [],
      possibleNextStages: ['grow-out'],
    },
    {
      id: 'grow-out',
      name: 'Grow-Out (45–60 Days)',
      typicalDurationDays: 52,
      color: '#10b981',
      inputs: [],
      activities: [
        'Inspect farm every 5–7 days',
        'Remove epiphytes, sediment, grazing fish waste',
        'Rotate lines to expose underside to light',
        'Replace any missing or dying clumps promptly',
        'Monitor ice-ice disease: bleached, limp thalli',
        'Watch for epiphyte overgrowth (green filamentous algae)',
        'Test growth rate: weigh sample clumps at Day 15 and Day 30',
      ],
      measurements: [
        { id: 'sample-weight', name: 'Sample Clump Weight', unit: 'g', frequency: 'weekly', required: true },
        { id: 'sgr', name: 'Specific Daily Growth Rate', unit: 'percent', frequency: 'weekly', required: true, benchmark: { min: 2.5, max: 4 } },
        { id: 'disease-pct', name: 'Ice-Ice Affected Thalli %', unit: 'percent', frequency: 'weekly', required: true, benchmark: { max: 5 } },
        { id: 'epiphyte', name: 'Epiphyte Cover %', unit: 'percent', frequency: 'weekly', required: false },
        { id: 'water-temp', name: 'Water Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 25, max: 30 } },
      ],
      outputs: [],
      possibleNextStages: ['harvest-sw'],
    },
    {
      id: 'harvest-sw',
      name: 'Harvest & Drying',
      typicalDurationDays: 7,
      color: '#047857',
      inputs: [],
      activities: [
        'Harvest at 45–60 days when biomass is 8–10× initial seed weight',
        'Untie and collect all thalli from longlines',
        'Weigh fresh harvest by block',
        'Retain 10–20% of best thalli for next seed cycle',
        'Sun-dry on nets or racks for 5–7 days to <25% moisture',
        'Stir/turn twice daily for even drying',
        'Bag and store in cool dry place',
        'Grade for colour and size before sale',
      ],
      measurements: [
        { id: 'fresh-total', name: 'Total Fresh Weight Harvested', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'dried-total', name: 'Dried Weight', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'moisture-sw', name: 'Dried Product Moisture', unit: 'percent', frequency: 'per_event', required: true, benchmark: { max: 25 } },
        { id: 'seed-retained', name: 'Seed Thalli Retained', unit: 'kg', frequency: 'per_event', required: true },
      ],
      outputs: [
        { id: 'fresh-seaweed', label: 'Fresh Seaweed', unit: 'kg', routingOptions: ['sale', 'processing'] },
        { id: 'dried-seaweed', label: 'Dried Seaweed', unit: 'kg', routingOptions: ['sale', 'inventory', 'processing'] },
        { id: 'seaweed-meal', label: 'Seaweed Meal / Powder', unit: 'kg', routingOptions: ['sale', 'processing'] },
      ],
      possibleNextStages: ['seeding'],
    },
  ],
};

// ─── SPIRULINA / MICROALGAE ──────────────────────────────────────────────────
export const spirulinaTemplate: ProductionTemplate = {
  id: 'spirulina-microalgae',
  name: 'Spirulina / Microalgae',
  shortName: 'Spirulina',
  category: 'aquatic_plants',
  species: 'Arthrospira platensis (Spirulina)',
  purpose: 'Nutrition Supplement & Aquaculture Feed',
  description:
    'Intensive raceway or tank cultivation of Spirulina for high-protein nutraceutical powder, animal feed additive, or aquaculture larval feed.',
  icon: '🧪',
  color: '#0d9488',
  tags: ['spirulina', 'microalgae', 'protein supplement', 'nutraceutical', 'raceway', 'aquafeed'],
  materials: [
    { id: 'spirulina-culture', name: 'Spirulina Starter Culture', unit: 'litre', category: 'input' },
    { id: 'growth-medium', name: 'Zarrouk Medium / Nutrients (NaHCO3, K2HPO4, NaNO3…)', unit: 'kg', category: 'input' },
    { id: 'co2-input', name: 'CO₂ Supplement (optional)', unit: 'kg', category: 'input' },
    { id: 'fresh-spirulina', name: 'Fresh Spirulina Paste', unit: 'kg', category: 'output' },
    { id: 'dried-powder', name: 'Dried Spirulina Powder', unit: 'kg', category: 'output' },
    { id: 'tablets', name: 'Spirulina Tablets / Capsules', unit: 'count', category: 'output' },
  ],
  kpis: [
    { id: 'productivity', name: 'Daily Biomass Productivity', unit: 'g', goodDirection: 'up', benchmark: 10 },
    { id: 'protein-pct', name: 'Protein Content (DW)', unit: 'percent', goodDirection: 'up', benchmark: 60 },
    { id: 'optical-density', name: 'Optical Density (OD680)', unit: 'ratio', goodDirection: 'up', benchmark: 0.8 },
    { id: 'contamination', name: 'Contamination Events per Quarter', unit: 'count', goodDirection: 'down', benchmark: 0 },
  ],
  stages: [
    {
      id: 'culture-build',
      name: 'Culture Build-Up (Inoculation → Stock)',
      typicalDurationDays: 14,
      color: '#ccfbf1',
      inputs: [
        { id: 'starter', label: 'Spirulina Starter Culture', unit: 'litre', required: true },
        { id: 'medium-small', label: 'Zarrouk Medium (laboratory grade)', unit: 'litre', required: true },
      ],
      activities: [
        'Start in 5–20 litre glass or transparent containers',
        'Prepare Zarrouk medium (standard salt formulation)',
        'Maintain pH 9.5–10.5 — Spirulina thrives in alkaline',
        'Provide continuous aeration with air pump',
        'Light 16h on / 8h off at 5,000–10,000 lux',
        'Build volume progressively to raceway scale over 2 weeks',
      ],
      measurements: [
        { id: 'od', name: 'Optical Density OD680', unit: 'ratio', frequency: 'daily', required: true, benchmark: { target: 0.5 } },
        { id: 'ph-c', name: 'pH', unit: 'ratio', frequency: 'daily', required: true, benchmark: { min: 9.5, max: 10.5 } },
        { id: 'temp-s', name: 'Culture Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 30, max: 35 } },
      ],
      outputs: [],
      possibleNextStages: ['continuous-harvest'],
    },
    {
      id: 'continuous-harvest',
      name: 'Continuous Production (Raceway / Tank)',
      typicalDurationDays: 365,
      color: '#14b8a6',
      inputs: [
        { id: 'nutrients', label: 'Nutrient Salts (NaHCO3, NaNO3, K2HPO4, etc.)', unit: 'kg', required: true },
        { id: 'water-evap', label: 'Water Replacement (evaporation top-up)', unit: 'litre', required: true },
        { id: 'co2', label: 'CO₂ Injection (optional — improves yield)', unit: 'kg', required: false },
      ],
      activities: [
        'Paddle-wheel raceway circulation 24h',
        'Add nutrients every 2–3 days based on growth rate',
        'Harvest 20–30% of culture volume daily (semi-continuous)',
        'Replace harvested volume with fresh medium',
        'Monitor for contamination: other algae, protozoa, bacteria',
        'Maintain salinity 18–20 g/L — evaporation concentrates salts',
        'Cover raceway at night in cold climates',
      ],
      measurements: [
        { id: 'od-daily', name: 'Daily OD680', unit: 'ratio', frequency: 'daily', required: true, benchmark: { min: 0.6, max: 1.0 } },
        { id: 'ph-daily', name: 'pH', unit: 'ratio', frequency: 'daily', required: true, benchmark: { min: 9.5, max: 10.5 } },
        { id: 'temp-daily', name: 'Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 28, max: 35 } },
        { id: 'harvest-volume', name: 'Volume Harvested', unit: 'litre', frequency: 'daily', required: true },
        { id: 'biomass-conc', name: 'Biomass Concentration (g/L)', unit: 'ratio', frequency: 'daily', required: false, benchmark: { target: 0.6 } },
        { id: 'contam-check', name: 'Contamination Check (microscopy)', unit: 'count', frequency: 'weekly', required: true },
      ],
      outputs: [],
      possibleNextStages: ['processing-drying'],
    },
    {
      id: 'processing-drying',
      name: 'Harvesting, Filtration & Drying',
      typicalDurationDays: 2,
      color: '#0f766e',
      inputs: [
        { id: 'filter-cloth', label: 'Filter Cloth / Centrifuge', unit: 'count', required: true },
        { id: 'dryer', label: 'Spray Dryer / Solar Dryer / Drum Dryer', unit: 'count', required: true },
      ],
      activities: [
        'Filter harvested culture through 40–80 µm mesh to get wet paste',
        'Or centrifuge at low speed for paste concentration',
        'Press out excess water to 80% moisture paste',
        'Dry immediately: spray dry (best), drum dry, or solar dry (lowest cost)',
        'Target dried powder ≤5% moisture for shelf stability',
        'Grind to fine powder, pack in opaque sealed bags',
        'Store at <25°C away from light',
        'Test protein content batch by batch',
      ],
      measurements: [
        { id: 'wet-paste', name: 'Wet Paste Weight', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'dried-pw', name: 'Dried Powder Yield', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'moisture-dry', name: 'Dried Powder Moisture', unit: 'percent', frequency: 'per_event', required: true, benchmark: { max: 5 } },
        { id: 'protein-test', name: 'Crude Protein Content', unit: 'percent', frequency: 'weekly', required: false, benchmark: { target: 60 } },
        { id: 'colour-q', name: 'Colour Score (green=5, brown=1)', unit: 'ratio', frequency: 'per_event', required: false },
      ],
      outputs: [
        { id: 'fresh-spirulina', label: 'Fresh Spirulina Paste', unit: 'kg', routingOptions: ['sale', 'processing', 'own_use'] },
        { id: 'dried-powder', label: 'Dried Spirulina Powder', unit: 'kg', routingOptions: ['sale', 'inventory', 'processing'] },
        { id: 'tablets', label: 'Tablets / Capsules', unit: 'count', routingOptions: ['sale', 'inventory'] },
      ],
      possibleNextStages: ['continuous-harvest'],
    },
  ],
};
