import { ProductionTemplate } from '../types';

export const maizeTemplate: ProductionTemplate = {
  id: 'maize',
  name: 'Maize (Field Crop)',
  shortName: 'Maize',
  category: 'crops',
  species: 'Maize',
  environment: 'open_field',
  description: 'Commercial maize production — land prep through harvest, drying, and storage.',
  icon: '🌽',
  color: 'yellow',
  tags: ['crops', 'maize', 'grain', 'staple'],
  materials: [
    { id: 'maize_seed', name: 'Maize Seed', unit: 'kg', category: 'input' },
    { id: 'fertiliser_basal', name: 'Basal Fertiliser (D-Compound)', unit: 'kg', category: 'input' },
    { id: 'fertiliser_top', name: 'Top Dressing (Urea/CAN)', unit: 'kg', category: 'input' },
    { id: 'herbicide', name: 'Herbicide', unit: 'litre', category: 'input' },
    { id: 'pesticide', name: 'Pesticide / Insecticide', unit: 'litre', category: 'input' },
    { id: 'maize_grain', name: 'Maize Grain', unit: 'tonne', category: 'output' },
    { id: 'maize_stover', name: 'Maize Stover (stalks)', unit: 'tonne', category: 'byproduct' },
    { id: 'maize_cob', name: 'Cobs (if separate)', unit: 'kg', category: 'byproduct' },
  ],
  kpis: [
    { id: 'yield_per_ha', name: 'Yield per Hectare', unit: 't/ha', goodDirection: 'up', benchmark: 6 },
    { id: 'cost_per_tonne', name: 'Cost per Tonne', unit: 'ZMW', goodDirection: 'down' },
    { id: 'revenue_per_ha', name: 'Revenue per Hectare', unit: 'ZMW', goodDirection: 'up' },
    { id: 'gross_margin', name: 'Gross Margin per ha', unit: 'ZMW', goodDirection: 'up' },
  ],
  stages: [
    {
      id: 'land_prep',
      name: 'Land Preparation',
      typicalDurationDays: 21,
      color: 'amber',
      inputs: [],
      activities: ['Ploughing / ripping', 'Disc harrowing', 'Ridging / bed preparation', 'Lime application if needed'],
      measurements: [
        { id: 'area_ha', name: 'Area Prepared (ha)', unit: 'ha', frequency: 'per_event', required: true },
        { id: 'soil_ph', name: 'Soil pH', unit: 'ratio', frequency: 'per_event', required: false, benchmark: { min: 5.5, max: 7 } },
      ],
      outputs: [],
      possibleNextStages: ['planting'],
    },
    {
      id: 'planting',
      name: 'Planting',
      typicalDurationDays: 7,
      color: 'green',
      inputs: [
        { id: 'maize_seed', label: 'Maize Seed', unit: 'kg', required: true },
        { id: 'fertiliser_basal', label: 'Basal Fertiliser', unit: 'kg', required: true },
      ],
      activities: ['Plant at recommended spacing', 'Apply basal fertiliser', 'Record planting date', 'Mark trial plots if any'],
      measurements: [
        { id: 'seed_rate', name: 'Seed Rate (kg/ha)', unit: 'kg', frequency: 'per_event', required: true, benchmark: { min: 20, max: 25 } },
        { id: 'plant_population', name: 'Plant Population (/ha)', unit: 'count', frequency: 'per_event', required: false, benchmark: { min: 44000, max: 53000 } },
      ],
      outputs: [],
      possibleNextStages: ['emergence'],
    },
    {
      id: 'emergence',
      name: 'Emergence & Establishment',
      typicalDurationDays: 10,
      color: 'lime',
      inputs: [],
      activities: ['Germination count', 'Gap filling', 'Weed control (pre-emergent)'],
      measurements: [
        { id: 'germination_pct', name: 'Germination %', unit: 'percent', frequency: 'per_event', required: true, benchmark: { min: 90 } },
        { id: 'gaps_pct', name: 'Gaps %', unit: 'percent', frequency: 'per_event', required: false },
      ],
      outputs: [],
      possibleNextStages: ['vegetative'],
    },
    {
      id: 'vegetative',
      name: 'Vegetative Growth',
      typicalDurationDays: 45,
      color: 'green',
      inputs: [
        { id: 'fertiliser_top', label: 'Top Dress Fertiliser', unit: 'kg', required: true },
        { id: 'herbicide', label: 'Herbicide', unit: 'litre', required: false },
        { id: 'pesticide', label: 'Pesticide', unit: 'litre', required: false },
      ],
      activities: ['Top dress at knee-height', 'Weed control', 'Scout for pests (FAW)', 'Irrigation if dry spell'],
      measurements: [
        { id: 'weed_pressure', name: 'Weed Pressure (1–5)', unit: 'ratio', frequency: 'weekly', required: false },
        { id: 'faw_incidence', name: 'FAW Incidence (%)', unit: 'percent', frequency: 'weekly', required: false },
        { id: 'rainfall', name: 'Weekly Rainfall (mm)', unit: 'ml', frequency: 'weekly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['tasseling'],
    },
    {
      id: 'tasseling',
      name: 'Tasselling & Silking',
      typicalDurationDays: 14,
      color: 'yellow',
      inputs: [],
      activities: ['Monitor tasselling date', 'Watch for silk cut', 'Irrigation critical period', 'Disease scouting'],
      measurements: [
        { id: 'tasseling_pct', name: 'Tasseling %', unit: 'percent', frequency: 'daily', required: false },
        { id: 'rainfall', name: 'Rainfall (mm)', unit: 'ml', frequency: 'daily', required: false },
      ],
      outputs: [],
      possibleNextStages: ['grain_fill'],
    },
    {
      id: 'grain_fill',
      name: 'Grain Fill & Maturity',
      typicalDurationDays: 45,
      color: 'orange',
      inputs: [],
      activities: ['Monitor grain development', 'Assess moisture content', 'Plan harvest logistics'],
      measurements: [
        { id: 'grain_moisture', name: 'Grain Moisture %', unit: 'percent', frequency: 'weekly', required: false, benchmark: { max: 14 } },
        { id: 'husk_cover', name: 'Husk Cover Score', unit: 'ratio', frequency: 'per_event', required: false },
      ],
      outputs: [],
      possibleNextStages: ['harvest'],
    },
    {
      id: 'harvest',
      name: 'Harvest',
      typicalDurationDays: 14,
      color: 'red',
      inputs: [],
      activities: ['Mechanised or manual harvest', 'Cob collection', 'Shelling', 'Weigh total', 'Record moisture at harvest'],
      measurements: [
        { id: 'yield_tonne', name: 'Yield (tonnes)', unit: 'tonne', frequency: 'per_event', required: true },
        { id: 'moisture_at_harvest', name: 'Moisture at Harvest (%)', unit: 'percent', frequency: 'per_event', required: true },
        { id: 'area_harvested', name: 'Area Harvested (ha)', unit: 'ha', frequency: 'per_event', required: true },
      ],
      outputs: [
        { id: 'maize_grain', label: 'Maize Grain', unit: 'tonne', routingOptions: ['sale', 'inventory', 'processing', 'own_use'] },
        { id: 'maize_stover', label: 'Stover', unit: 'tonne', routingOptions: ['sale', 'own_use', 'waste'] },
      ],
      possibleNextStages: ['drying_storage'],
    },
    {
      id: 'drying_storage',
      name: 'Drying & Storage',
      typicalDurationDays: 21,
      color: 'slate',
      inputs: [],
      activities: ['Sun-dry or mechanical dry', 'Check moisture before bagging', 'Apply storage chemicals', 'Record into store'],
      measurements: [
        { id: 'moisture_final', name: 'Final Moisture %', unit: 'percent', frequency: 'per_event', required: true, benchmark: { max: 13 } },
        { id: 'bags_stored', name: 'Bags Stored (50kg)', unit: 'bag', frequency: 'per_event', required: true },
      ],
      outputs: [],
      possibleNextStages: [],
    },
  ],
};

export const soybeanTemplate: ProductionTemplate = {
  id: 'soybean',
  name: 'Soybean',
  shortName: 'Soybean',
  category: 'crops',
  species: 'Soybean',
  environment: 'open_field',
  description: 'Soybean production for grain and protein meal.',
  icon: '🫘',
  color: 'lime',
  tags: ['crops', 'soybean', 'legume', 'protein'],
  materials: [
    { id: 'soy_seed', name: 'Soybean Seed', unit: 'kg', category: 'input' },
    { id: 'rhizobium', name: 'Rhizobium Inoculant', unit: 'g', category: 'input' },
    { id: 'soy_grain', name: 'Soybean Grain', unit: 'tonne', category: 'output' },
  ],
  kpis: [
    { id: 'yield_per_ha', name: 'Yield per Hectare', unit: 't/ha', goodDirection: 'up', benchmark: 2.5 },
    { id: 'protein_content', name: 'Protein Content', unit: '%', goodDirection: 'up', benchmark: 38 },
    { id: 'gross_margin', name: 'Gross Margin per ha', unit: 'ZMW', goodDirection: 'up' },
  ],
  stages: [
    {
      id: 'planting',
      name: 'Planting',
      typicalDurationDays: 7,
      color: 'lime',
      inputs: [
        { id: 'soy_seed', label: 'Soybean Seed', unit: 'kg', required: true },
        { id: 'rhizobium', label: 'Rhizobium Inoculant', unit: 'g', required: true },
      ],
      activities: ['Inoculate seed with rhizobium', 'Plant at 45×5cm spacing', 'Basal fertiliser (P only)'],
      measurements: [
        { id: 'area_ha', name: 'Area Planted (ha)', unit: 'ha', frequency: 'per_event', required: true },
      ],
      outputs: [],
      possibleNextStages: ['vegetative'],
    },
    {
      id: 'vegetative',
      name: 'Vegetative Growth',
      typicalDurationDays: 50,
      color: 'green',
      inputs: [],
      activities: ['Weed control', 'Pest scouting', 'Foliar feeding if needed'],
      measurements: [
        { id: 'nodule_count', name: 'Root Nodule Count', unit: 'count', frequency: 'per_event', required: false },
      ],
      outputs: [],
      possibleNextStages: ['harvest'],
    },
    {
      id: 'harvest',
      name: 'Harvest',
      typicalDurationDays: 10,
      color: 'amber',
      inputs: [],
      activities: ['Harvest when 95% pods brown', 'Thresh and clean', 'Weigh and bag'],
      measurements: [
        { id: 'yield_tonne', name: 'Yield (tonnes)', unit: 'tonne', frequency: 'per_event', required: true },
        { id: 'moisture', name: 'Moisture %', unit: 'percent', frequency: 'per_event', required: true },
      ],
      outputs: [
        { id: 'soy_grain', label: 'Soybean Grain', unit: 'tonne', routingOptions: ['sale', 'inventory', 'processing', 'own_use'] },
      ],
      possibleNextStages: [],
    },
  ],
};
