// ─────────────────────────────────────────────────────────────────────────────
// Forestry & Agroforestry Templates
// Maps to Universal Templates T4 (Forestry) and T5 (Agroforestry / Mixed)
// Covers: Timber Forestry, Agroforestry / Silvopastoral
// ─────────────────────────────────────────────────────────────────────────────
import type { ProductionTemplate } from '../types';

// ─── TIMBER FORESTRY ─────────────────────────────────────────────────────────
export const timberForestryTemplate: ProductionTemplate = {
  id: 'timber-forestry',
  name: 'Timber Forestry',
  shortName: 'Timber',
  category: 'forestry',
  species: 'Eucalyptus / Pine / Teak / Mukula (configurable)',
  purpose: 'Timber, Poles, Charcoal & Carbon Credits',
  description:
    'Long-rotation timber plantation management. Tracks planting, establishment, thinning, and final harvest. Multi-decade cycle with short-term income from thinnings.',
  icon: '🌲',
  color: '#166534',
  tags: ['forestry', 'timber', 'eucalyptus', 'pine', 'teak', 'poles', 'charcoal', 'carbon'],
  materials: [
    { id: 'seedlings', name: 'Tree Seedlings', unit: 'count', category: 'input' },
    { id: 'fertiliser-t', name: 'Fertiliser (basal application)', unit: 'kg', category: 'input' },
    { id: 'herbicide', name: 'Herbicide / Weed Control', unit: 'litre', category: 'input' },
    { id: 'timber-log', name: 'Timber Logs (m³)', unit: 'm3', category: 'output' },
    { id: 'poles', name: 'Utility Poles', unit: 'count', category: 'output' },
    { id: 'firewood', name: 'Firewood', unit: 'kg', category: 'output' },
    { id: 'charcoal', name: 'Charcoal', unit: 'kg', category: 'output' },
    { id: 'carbon-credits', name: 'Carbon Credits (VCS / REDD+)', unit: 'count', category: 'output' },
    { id: 'thinning-poles', name: 'Thinning Poles (intermediate income)', unit: 'count', category: 'output' },
  ],
  kpis: [
    { id: 'mai', name: 'Mean Annual Increment (m³/ha/year)', unit: 'ratio', goodDirection: 'up', benchmark: 15 },
    { id: 'survival-rate', name: 'Survival Rate at 3 Years', unit: 'percent', goodDirection: 'up', benchmark: 85 },
    { id: 'dbh', name: 'Mean Diameter at Breast Height (DBH)', unit: 'g', goodDirection: 'up', benchmark: 20 },
    { id: 'stocking-density', name: 'Stocking Density at Final Harvest', unit: 'count', goodDirection: 'neutral', benchmark: 800 },
  ],
  stages: [
    {
      id: 'site-prep-f',
      name: 'Site Preparation',
      typicalDurationDays: 60,
      color: '#dcfce7',
      inputs: [
        { id: 'land-clear', label: 'Land Clearing / Burning (where applicable)', unit: 'ha', required: false },
        { id: 'lines', label: 'Line-Marking / Pegging', unit: 'ha', required: true },
      ],
      activities: [
        'Map planting area using GPS/drone',
        'Mark planting lines and hole positions at target spacing (e.g. 3×3 m, 2×3 m)',
        'Rip soil or pit-dig (60×60×60 cm) per tree',
        'Apply basal fertiliser in planting hole if needed',
        'Prepare firebreaks around perimeter',
        'Source certified seedlings from registered nursery',
      ],
      measurements: [
        { id: 'area-ha', name: 'Area Prepared (ha)', unit: 'ha', frequency: 'per_event', required: true },
        { id: 'holes-dug', name: 'Holes Prepared', unit: 'count', frequency: 'per_event', required: true },
        { id: 'spacing', name: 'Planting Spacing (m × m)', unit: 'ratio', frequency: 'per_event', required: true },
      ],
      outputs: [],
      possibleNextStages: ['planting'],
    },
    {
      id: 'planting',
      name: 'Planting',
      typicalDurationDays: 30,
      color: '#bbf7d0',
      inputs: [
        { id: 'seedlings-p', label: 'Seedlings (certified quality, 30–60 cm)', unit: 'count', required: true },
        { id: 'fert-basal', label: 'Basal Fertiliser per Hole', unit: 'kg', required: false },
      ],
      activities: [
        'Plant at start of rainy season',
        'Place seedling in centre of hole; firm soil around roots',
        'Apply fertiliser in ring around seedling (not touching stem)',
        'Water if not raining within 48h',
        'Record GPS coordinate of planting block',
        'Complete planting within 4 weeks of land prep',
      ],
      measurements: [
        { id: 'seedlings-planted', name: 'Seedlings Planted', unit: 'count', frequency: 'per_event', required: true },
        { id: 'seedlings-per-ha', name: 'Seedlings per Hectare', unit: 'count', frequency: 'per_event', required: true },
        { id: 'fert-applied', name: 'Fertiliser Applied (kg/tree)', unit: 'kg', frequency: 'per_event', required: false },
      ],
      outputs: [],
      possibleNextStages: ['establishment'],
    },
    {
      id: 'establishment',
      name: 'Establishment (Years 1–3)',
      typicalDurationDays: 1095,
      color: '#86efac',
      inputs: [
        { id: 'weed-ctrl', label: 'Weeding (manual/chemical)', unit: 'ha', required: true },
        { id: 'replanting', label: 'Replacement Seedlings (for failures)', unit: 'count', required: false },
        { id: 'fert-top', label: 'Top-Dressing Fertiliser', unit: 'kg', required: false },
      ],
      activities: [
        'Weed around tree base (1 m radius) in first 2 years 3× per year',
        'Replace dead/failed seedlings within first 6 months',
        'Apply top-dressing fertiliser at 6 months and 12 months',
        'Control competing vegetation with strip-weeding or herbicide',
        'Assess survival rate at 6, 12, and 24 months',
        'Report area stocked to forestry authority if required',
      ],
      measurements: [
        { id: 'survival', name: 'Survival Rate', unit: 'percent', frequency: 'monthly', required: true, benchmark: { min: 80 } },
        { id: 'height', name: 'Mean Tree Height (m)', unit: 'ratio', frequency: 'monthly', required: true },
        { id: 'weed-cover', name: 'Weed Cover (%)', unit: 'percent', frequency: 'monthly', required: false, benchmark: { max: 30 } },
      ],
      outputs: [],
      possibleNextStages: ['thinning'],
    },
    {
      id: 'thinning',
      name: 'Thinning (Years 4–8)',
      typicalDurationDays: 730,
      color: '#4ade80',
      inputs: [
        { id: 'chainsaw', label: 'Chainsaw / Hand Labour', unit: 'count', required: true },
      ],
      activities: [
        'First thinning at Year 4–5: remove 30–40% of stems (worst trees)',
        'Mark trees for removal: leaning, forked, suppressed',
        'Use removed stems for poles, fence posts, firewood',
        'Second thinning at Year 6–8: reduce to final stocking density',
        'Prune remaining crop trees to 6 m clear bole (high-value timber)',
        'Firebreak maintenance annually',
      ],
      measurements: [
        { id: 'dbh-thin', name: 'Mean DBH at Thinning', unit: 'g', frequency: 'per_event', required: true },
        { id: 'stems-removed', name: 'Stems Removed per Hectare', unit: 'count', frequency: 'per_event', required: true },
        { id: 'pole-yield', name: 'Pole / Firewood Yield from Thinning', unit: 'count', frequency: 'per_event', required: true },
        { id: 'basal-area', name: 'Basal Area (m²/ha)', unit: 'ratio', frequency: 'per_event', required: false },
      ],
      outputs: [
        { id: 'thinning-poles', label: 'Thinning Poles / Fenceposts', unit: 'count', routingOptions: ['sale', 'own_use'] },
        { id: 'firewood', label: 'Firewood from Thinnings', unit: 'kg', routingOptions: ['sale', 'own_use', 'processing'] },
      ],
      possibleNextStages: ['final-harvest'],
    },
    {
      id: 'final-harvest',
      name: 'Final Harvest (Clearfell)',
      typicalDurationDays: 180,
      color: '#16a34a',
      inputs: [
        { id: 'harvest-equip', label: 'Harvesting Equipment / Chainsaw Teams', unit: 'count', required: true },
        { id: 'transport', label: 'Timber Transport (tractor, truck)', unit: 'count', required: true },
      ],
      activities: [
        'Contract-out or manage direct felling and extraction',
        'Cross-cut logs to mill specifications (lengths vary by market)',
        'Stack and grade at log landing',
        'Sample 10% of logs for volume measurement (cruising)',
        'Arrange timber sale to mill or direct buyer',
        'Leave logging slash to decompose (or burn in designated way)',
        'Record total timber volume (m³) and revenue',
        'Decision: coppice (Eucalyptus) or replant new crop',
      ],
      measurements: [
        { id: 'vol-harvest', name: 'Timber Volume Harvested (m³)', unit: 'm3', frequency: 'per_event', required: true },
        { id: 'dbh-final', name: 'Mean DBH at Harvest', unit: 'g', frequency: 'per_event', required: true },
        { id: 'height-final', name: 'Mean Height at Harvest (m)', unit: 'ratio', frequency: 'per_event', required: true },
        { id: 'mai-final', name: 'Mean Annual Increment (m³/ha/yr)', unit: 'ratio', frequency: 'per_event', required: true },
      ],
      outputs: [
        { id: 'timber-log', label: 'Timber Logs (m³)', unit: 'm3', routingOptions: ['sale', 'processing'] },
        { id: 'poles', label: 'Utility Poles', unit: 'count', routingOptions: ['sale', 'inventory'] },
        { id: 'firewood', label: 'Firewood / Offcuts', unit: 'kg', routingOptions: ['sale', 'own_use', 'processing'] },
        { id: 'charcoal', label: 'Charcoal (if kiln on site)', unit: 'kg', routingOptions: ['sale', 'processing'] },
      ],
      possibleNextStages: ['planting'],
    },
  ],
};

// ─── AGROFORESTRY / SILVOPASTORAL ────────────────────────────────────────────
export const agroforestryTemplate: ProductionTemplate = {
  id: 'agroforestry',
  name: 'Agroforestry / Silvopastoral',
  shortName: 'Agroforestry',
  category: 'forestry',
  purpose: 'Multiple-Enterprise Integration: Trees + Crops + Livestock',
  description:
    'Integrated land-use system combining trees with crops and/or livestock on the same block. Tracks all three sub-enterprises and their interactions (shade, fertiliser, feed, soil).',
  icon: '🌳',
  color: '#14532d',
  tags: ['agroforestry', 'silvopastoral', 'mixed farming', 'integration', 'trees', 'shade', 'carbon'],
  materials: [
    { id: 'tree-seedlings', name: 'Tree Seedlings (fruit/timber/leguminous)', unit: 'count', category: 'input' },
    { id: 'crop-seed', name: 'Crop Seed / Planting Material', unit: 'kg', category: 'input' },
    { id: 'livestock-stock', name: 'Livestock (grazers)', unit: 'head', category: 'input' },
    { id: 'timber-af', name: 'Timber / Poles (from trees)', unit: 'm3', category: 'output' },
    { id: 'crop-yield', name: 'Crop Yield (grain / vegetable / fruit)', unit: 'kg', category: 'output' },
    { id: 'livestock-product', name: 'Livestock Products (meat / milk / eggs)', unit: 'kg', category: 'output' },
    { id: 'biomass-fodder', name: 'Biomass / Fodder (from tree prunings)', unit: 'kg', category: 'output' },
    { id: 'firewood-af', name: 'Firewood (prunings)', unit: 'kg', category: 'output' },
    { id: 'carbon-af', name: 'Carbon Credits', unit: 'count', category: 'output' },
  ],
  kpis: [
    { id: 'land-equiv', name: 'Land Equivalent Ratio (LER)', unit: 'ratio', goodDirection: 'up', benchmark: 1.3 },
    { id: 'soil-organic', name: 'Soil Organic Carbon (t/ha)', unit: 'tonne', goodDirection: 'up', benchmark: 3 },
    { id: 'tree-canopy', name: 'Tree Canopy Cover (%)', unit: 'percent', goodDirection: 'neutral', benchmark: 30 },
    { id: 'crop-yield-af', name: 'Intercrop Yield (% of monoculture)', unit: 'percent', goodDirection: 'up', benchmark: 80 },
  ],
  stages: [
    {
      id: 'design-plan',
      name: 'System Design & Planning',
      typicalDurationDays: 30,
      color: '#f0fdf4',
      inputs: [],
      activities: [
        'Define objectives: timber + grain, fruit + livestock, or full silvopastoral',
        'Select compatible tree-crop-livestock combinations',
        'Map block: tree rows (E-W orientation reduces shading of crops)',
        'Design alley widths (6–12 m for machinery; 3–5 m for smallholder)',
        'Plan tree spacing: 5–10 m within rows, 10–20 m between rows',
        'Obtain soil test results — baseline for fertility tracking',
        'Register with carbon scheme if carbon revenue is a goal',
      ],
      measurements: [
        { id: 'area-planned', name: 'Area Under Agroforestry (ha)', unit: 'ha', frequency: 'per_event', required: true },
        { id: 'tree-density', name: 'Tree Density (trees/ha)', unit: 'count', frequency: 'per_event', required: true, benchmark: { target: 100 } },
        { id: 'soil-ph', name: 'Baseline Soil pH', unit: 'ratio', frequency: 'per_event', required: false },
        { id: 'soil-carbon', name: 'Baseline Soil Organic Carbon (%)', unit: 'percent', frequency: 'per_event', required: false },
      ],
      outputs: [],
      possibleNextStages: ['tree-planting'],
    },
    {
      id: 'tree-planting',
      name: 'Tree Establishment',
      typicalDurationDays: 365,
      color: '#dcfce7',
      inputs: [
        { id: 'trees', label: 'Tree Seedlings (leguminous / fruit / timber)', unit: 'count', required: true },
        { id: 'mulch', label: 'Mulch / Compost for Tree Base', unit: 'kg', required: false },
      ],
      activities: [
        'Plant trees at start of rainy season at planned spacing',
        'Mulch tree bases to suppress weeds and retain moisture',
        'Protect young trees from grazing animals — use tree guards',
        'Prune leguminous trees after 6 months — biomass to alley',
        'Intercrop annual crops between tree rows from Year 1',
        'Monitor tree-crop competition for light and water',
      ],
      measurements: [
        { id: 'tree-survival', name: 'Tree Survival Rate', unit: 'percent', frequency: 'monthly', required: true, benchmark: { min: 80 } },
        { id: 'tree-height', name: 'Mean Tree Height (m)', unit: 'ratio', frequency: 'monthly', required: true },
        { id: 'canopy-cover', name: 'Canopy Cover (%)', unit: 'percent', frequency: 'monthly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['crop-integration'],
    },
    {
      id: 'crop-integration',
      name: 'Crop & Livestock Integration (Ongoing)',
      typicalDurationDays: 365,
      color: '#86efac',
      inputs: [
        { id: 'crop-inputs', label: 'Crop Planting Materials / Inputs', unit: 'kg', required: true },
        { id: 'grazing-mgmt', label: 'Livestock Grazing Management', unit: 'count', required: false },
      ],
      activities: [
        'Plant inter-row crops each season as normal',
        'Use pruned tree biomass as green manure / mulch for crops',
        'Integrate livestock: graze alley crops after harvest or on cover crops',
        'Manage grazing to prevent tree damage (rotational grazing)',
        'Collect manure data for nutrient cycling records',
        'Monitor alley soil for improvement in organic matter over time',
        'Adjust alley width if trees are shading crops excessively',
        'Prune trees annually to control shade and harvest fodder',
      ],
      measurements: [
        { id: 'intercrop-yield', name: 'Inter-row Crop Yield', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'livestock-gain', name: 'Livestock Liveweight Gain (if grazing)', unit: 'kg', frequency: 'monthly', required: false },
        { id: 'tree-height-yr', name: 'Tree Height (m)', unit: 'ratio', frequency: 'monthly', required: true },
        { id: 'soil-test-y', name: 'Soil Organic Carbon Annual Test', unit: 'percent', frequency: 'as_needed', required: false },
        { id: 'fodder-pruning', name: 'Fodder from Prunings', unit: 'kg', frequency: 'as_needed', required: false },
      ],
      outputs: [
        { id: 'crop-yield', label: 'Intercrop Yield', unit: 'kg', routingOptions: ['sale', 'own_use', 'inventory'] },
        { id: 'livestock-product', label: 'Livestock Products', unit: 'kg', routingOptions: ['sale', 'own_use'] },
        { id: 'biomass-fodder', label: 'Biomass / Fodder from Prunings', unit: 'kg', routingOptions: ['own_use', 'sale'] },
        { id: 'firewood-af', label: 'Firewood from Prunings', unit: 'kg', routingOptions: ['own_use', 'sale'] },
      ],
      possibleNextStages: ['crop-integration', 'tree-harvest'],
    },
    {
      id: 'tree-harvest',
      name: 'Tree Harvest (Timber / Fruit / Poles)',
      typicalDurationDays: 60,
      color: '#16a34a',
      inputs: [],
      activities: [
        'Harvest timber trees when target diameter/maturity reached',
        'Selective harvest (individual trees) or strip-felling if designed for rotation',
        'Leave at least 50% of trees for continued agroforestry function',
        'Replant harvested row within one season',
        'Record timber/fruit yield per tree species separately',
        'Update carbon accounting if registered for credits',
      ],
      measurements: [
        { id: 'timber-vol', name: 'Timber Volume (m³)', unit: 'm3', frequency: 'per_event', required: false },
        { id: 'fruit-yield', name: 'Fruit Yield (kg)', unit: 'kg', frequency: 'per_event', required: false },
        { id: 'trees-remaining', name: 'Trees Remaining Post-Harvest', unit: 'count', frequency: 'per_event', required: true },
      ],
      outputs: [
        { id: 'timber-af', label: 'Timber / Poles', unit: 'm3', routingOptions: ['sale', 'own_use', 'processing'] },
        { id: 'crop-yield', label: 'Tree Fruit / Products', unit: 'kg', routingOptions: ['sale', 'processing', 'inventory'] },
        { id: 'carbon-af', label: 'Carbon Credits', unit: 'count', routingOptions: ['sale'] },
      ],
      possibleNextStages: ['crop-integration'],
    },
  ],
};
