import { ProductionTemplate } from '../types';

export const tomatoTemplate: ProductionTemplate = {
  id: 'tomato',
  name: 'Tomato',
  shortName: 'Tomato',
  category: 'horticulture',
  species: 'Tomato',
  environment: 'open_field',
  description: 'Tomato production — nursery through harvest, grading, and market.',
  icon: '🍅',
  color: 'red',
  tags: ['horticulture', 'tomato', 'vegetable', 'fresh-produce'],
  materials: [
    { id: 'tomato_seed', name: 'Tomato Seed', unit: 'g', category: 'input' },
    { id: 'transplant', name: 'Transplants / Seedlings', unit: 'count', category: 'intermediate' },
    { id: 'fertiliser', name: 'Fertiliser', unit: 'kg', category: 'input' },
    { id: 'pesticide', name: 'Pesticide / Fungicide', unit: 'litre', category: 'input' },
    { id: 'irrigation_water', name: 'Irrigation Water', unit: 'litre', category: 'input' },
    { id: 'fresh_tomato', name: 'Fresh Tomatoes (Grade A)', unit: 'kg', category: 'output', perishable: true },
    { id: 'grade_b_tomato', name: 'Grade B Tomatoes', unit: 'kg', category: 'output', perishable: true },
    { id: 'tomato_waste', name: 'Culls / Waste', unit: 'kg', category: 'waste' },
  ],
  kpis: [
    { id: 'yield_per_ha', name: 'Yield per Hectare', unit: 't/ha', goodDirection: 'up', benchmark: 30 },
    { id: 'grade_a_pct', name: 'Grade A %', unit: '%', goodDirection: 'up', benchmark: 70 },
    { id: 'cost_per_kg', name: 'Cost per kg', unit: 'ZMW', goodDirection: 'down' },
    { id: 'revenue_per_ha', name: 'Revenue per ha', unit: 'ZMW', goodDirection: 'up' },
  ],
  stages: [
    {
      id: 'nursery',
      name: 'Nursery',
      typicalDurationDays: 28,
      color: 'lime',
      inputs: [
        { id: 'tomato_seed', label: 'Tomato Seed', unit: 'g', required: true },
      ],
      activities: ['Prepare nursery beds', 'Sow seed', 'Watering and shade management', 'Apply starter fertiliser', 'Harden off seedlings'],
      measurements: [
        { id: 'germination_pct', name: 'Germination %', unit: 'percent', frequency: 'per_event', required: true, benchmark: { min: 85 } },
        { id: 'seedling_height', name: 'Seedling Height (cm)', unit: 'count', frequency: 'weekly', required: false, benchmark: { target: 15 } },
      ],
      outputs: [
        { id: 'transplant', label: 'Transplants', unit: 'count', routingOptions: ['inventory', 'transfer', 'sale'] },
      ],
      possibleNextStages: ['transplant'],
    },
    {
      id: 'transplant',
      name: 'Land Prep & Transplanting',
      typicalDurationDays: 7,
      color: 'green',
      inputs: [
        { id: 'transplant', label: 'Transplants', unit: 'count', required: true },
        { id: 'fertiliser', label: 'Basal Fertiliser', unit: 'kg', required: true },
      ],
      activities: ['Prepare beds / ridges', 'Apply basal fertiliser', 'Transplant at 60×30cm', 'Irrigate immediately', 'Stake / trellis setup'],
      measurements: [
        { id: 'plants_transplanted', name: 'Plants Transplanted', unit: 'count', frequency: 'per_event', required: true },
        { id: 'plant_survival_pct', name: 'Survival after 7 days %', unit: 'percent', frequency: 'per_event', required: true },
        { id: 'area_ha', name: 'Area Transplanted (ha)', unit: 'ha', frequency: 'per_event', required: true },
      ],
      outputs: [],
      possibleNextStages: ['vegetative'],
    },
    {
      id: 'vegetative',
      name: 'Vegetative Growth',
      typicalDurationDays: 30,
      color: 'emerald',
      inputs: [
        { id: 'fertiliser', label: 'Top Dress / Foliar Feed', unit: 'kg', required: true },
        { id: 'pesticide', label: 'Fungicide / Insecticide', unit: 'litre', required: false },
        { id: 'irrigation_water', label: 'Irrigation', unit: 'litre', required: true },
      ],
      activities: ['Pruning and suckering', 'Tying to stakes', 'Irrigation every 2–3 days', 'Disease scouting (blight, wilt)', 'Pest scouting'],
      measurements: [
        { id: 'plant_height', name: 'Average Plant Height (cm)', unit: 'count', frequency: 'weekly', required: false },
        { id: 'spray_count', name: 'Sprays Applied', unit: 'count', frequency: 'weekly', required: false },
        { id: 'irrigation_litres', name: 'Irrigation Applied (L)', unit: 'litre', frequency: 'weekly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['flowering'],
    },
    {
      id: 'flowering',
      name: 'Flowering & Fruit Set',
      typicalDurationDays: 21,
      color: 'yellow',
      inputs: [
        { id: 'fertiliser', label: 'Potassium-rich Fertiliser', unit: 'kg', required: true },
        { id: 'pesticide', label: 'Fungicide / Insecticide', unit: 'litre', required: false },
      ],
      activities: ['Monitor fruit set %', 'Calcium foliar spray', 'Scout for early blight, thrips, leaf miner', 'Continue irrigation'],
      measurements: [
        { id: 'fruit_set_pct', name: 'Fruit Set %', unit: 'percent', frequency: 'weekly', required: false, benchmark: { min: 60 } },
        { id: 'blossom_end_rot', name: 'Blossom End Rot Incidence', unit: 'percent', frequency: 'weekly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['harvest'],
    },
    {
      id: 'harvest',
      name: 'Harvest & Grading',
      typicalDurationDays: 45,
      color: 'red',
      inputs: [],
      activities: ['Harvest at pink/light red stage', 'Grade A/B/C on field', 'Pack in crates', 'Cold store or dispatch same day'],
      measurements: [
        { id: 'kg_harvested', name: 'Total kg Harvested', unit: 'kg', frequency: 'daily', required: true },
        { id: 'grade_a_kg', name: 'Grade A (kg)', unit: 'kg', frequency: 'daily', required: true },
        { id: 'grade_b_kg', name: 'Grade B (kg)', unit: 'kg', frequency: 'daily', required: true },
        { id: 'waste_kg', name: 'Culls / Waste (kg)', unit: 'kg', frequency: 'daily', required: false },
        { id: 'price_per_kg', name: 'Market Price per kg', unit: 'kg', frequency: 'daily', required: true },
      ],
      outputs: [
        { id: 'fresh_tomato', label: 'Fresh Tomatoes (Grade A)', unit: 'kg', routingOptions: ['sale', 'inventory', 'processing'] },
        { id: 'grade_b_tomato', label: 'Grade B Tomatoes', unit: 'kg', routingOptions: ['sale', 'processing'] },
        { id: 'tomato_waste', label: 'Culls / Waste', unit: 'kg', routingOptions: ['waste', 'own_use'] },
      ],
      possibleNextStages: [],
    },
  ],
};

export const onionTemplate: ProductionTemplate = {
  id: 'onion',
  name: 'Onion',
  shortName: 'Onion',
  category: 'horticulture',
  species: 'Onion',
  environment: 'open_field',
  description: 'Onion production — from seed or sets through curing and market.',
  icon: '🧅',
  color: 'purple',
  tags: ['horticulture', 'onion', 'vegetable', 'bulb'],
  materials: [
    { id: 'onion_seed', name: 'Onion Seed / Sets', unit: 'kg', category: 'input' },
    { id: 'fertiliser', name: 'Fertiliser', unit: 'kg', category: 'input' },
    { id: 'onion_bulb', name: 'Onion Bulbs', unit: 'kg', category: 'output', perishable: true },
  ],
  kpis: [
    { id: 'yield_per_ha', name: 'Yield per Hectare', unit: 't/ha', goodDirection: 'up', benchmark: 25 },
    { id: 'marketable_pct', name: 'Marketable %', unit: '%', goodDirection: 'up', benchmark: 80 },
    { id: 'revenue_per_ha', name: 'Revenue per ha', unit: 'ZMW', goodDirection: 'up' },
  ],
  stages: [
    {
      id: 'nursery',
      name: 'Nursery / Direct Sowing',
      typicalDurationDays: 42,
      color: 'purple',
      inputs: [{ id: 'onion_seed', label: 'Onion Seed', unit: 'kg', required: true }],
      activities: ['Sow in nursery beds', 'Water daily', 'Thin to 3cm', 'Harden for transplant'],
      measurements: [
        { id: 'germination_pct', name: 'Germination %', unit: 'percent', frequency: 'per_event', required: true },
      ],
      outputs: [],
      possibleNextStages: ['transplant'],
    },
    {
      id: 'transplant',
      name: 'Transplanting & Bulbing',
      typicalDurationDays: 90,
      color: 'violet',
      inputs: [{ id: 'fertiliser', label: 'Fertiliser', unit: 'kg', required: true }],
      activities: ['Transplant at 10×10cm', 'Top dressing at 3 and 6 weeks', 'Irrigation 2–3x per week', 'Weed control'],
      measurements: [
        { id: 'bulb_diameter', name: 'Average Bulb Diameter (cm)', unit: 'count', frequency: 'weekly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['harvest'],
    },
    {
      id: 'harvest',
      name: 'Harvest & Curing',
      typicalDurationDays: 14,
      color: 'amber',
      inputs: [],
      activities: ['Harvest at 50–75% tops down', 'Cure in field 7–10 days', 'Grade and bag', 'Pack for market or storage'],
      measurements: [
        { id: 'yield_kg', name: 'Total Yield (kg)', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'marketable_pct', name: 'Marketable %', unit: 'percent', frequency: 'per_event', required: true },
      ],
      outputs: [
        { id: 'onion_bulb', label: 'Onion Bulbs', unit: 'kg', routingOptions: ['sale', 'inventory', 'processing'] },
      ],
      possibleNextStages: [],
    },
  ],
};

export const mangoTemplate: ProductionTemplate = {
  id: 'mango_orchard',
  name: 'Mango Orchard',
  shortName: 'Mango',
  category: 'orchard',
  species: 'Mango',
  environment: 'orchard',
  description: 'Mango orchard management — establishment, flowering, and seasonal harvests.',
  icon: '🥭',
  color: 'orange',
  tags: ['orchard', 'mango', 'fruit', 'perennial'],
  materials: [
    { id: 'mango_tree', name: 'Mango Trees', unit: 'count', category: 'input' },
    { id: 'orchard_fertiliser', name: 'Orchard Fertiliser', unit: 'kg', category: 'input' },
    { id: 'fresh_mango', name: 'Fresh Mango (Grade A)', unit: 'kg', category: 'output', perishable: true },
    { id: 'grade_b_mango', name: 'Grade B Mango', unit: 'kg', category: 'output', perishable: true },
  ],
  kpis: [
    { id: 'yield_per_tree', name: 'Yield per Tree', unit: 'kg', goodDirection: 'up', benchmark: 100 },
    { id: 'grade_a_pct', name: 'Grade A %', unit: '%', goodDirection: 'up', benchmark: 65 },
    { id: 'revenue_per_ha', name: 'Revenue per ha', unit: 'ZMW', goodDirection: 'up' },
  ],
  stages: [
    {
      id: 'flowering',
      name: 'Flowering & Fruit Set',
      typicalDurationDays: 30,
      color: 'pink',
      inputs: [{ id: 'orchard_fertiliser', label: 'Potassium Fertiliser', unit: 'kg', required: false }],
      activities: ['Monitor flower development', 'Pest management (mango hoppers)', 'Calcium spray', 'Thin if too dense'],
      measurements: [
        { id: 'flowering_pct', name: 'Trees in Flower %', unit: 'percent', frequency: 'weekly', required: true },
        { id: 'fruit_set_pct', name: 'Fruit Set %', unit: 'percent', frequency: 'per_event', required: false },
      ],
      outputs: [],
      possibleNextStages: ['fruit_development'],
    },
    {
      id: 'fruit_development',
      name: 'Fruit Development',
      typicalDurationDays: 90,
      color: 'orange',
      inputs: [{ id: 'orchard_fertiliser', label: 'Fertiliser', unit: 'kg', required: false }],
      activities: ['Fruit fly baiting', 'Ant control', 'Irrigation during dry spells', 'Bag high-value fruits'],
      measurements: [
        { id: 'avg_fruit_weight', name: 'Avg Fruit Weight (g)', unit: 'g', frequency: 'weekly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['harvest'],
    },
    {
      id: 'harvest',
      name: 'Harvest & Grading',
      typicalDurationDays: 21,
      color: 'amber',
      inputs: [],
      activities: ['Harvest at mature green stage', 'Grade A/B by size and blemish', 'Pack in crates', 'Cold store or dispatch'],
      measurements: [
        { id: 'total_kg', name: 'Total Harvested (kg)', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'grade_a_kg', name: 'Grade A (kg)', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'price_per_kg', name: 'Sale Price per kg', unit: 'kg', frequency: 'per_event', required: true },
      ],
      outputs: [
        { id: 'fresh_mango', label: 'Fresh Mango (Grade A)', unit: 'kg', routingOptions: ['sale', 'inventory', 'processing'] },
        { id: 'grade_b_mango', label: 'Grade B', unit: 'kg', routingOptions: ['sale', 'processing'] },
      ],
      possibleNextStages: [],
    },
  ],
};
