// ─────────────────────────────────────────────────────────────────────────────
// Insects & Worms Templates
// Maps to Universal Template T10 — Colony / Small Organism
// Covers: BSF, Cricket, Mealworm, Silkworm, Vermiculture, Snail
// ─────────────────────────────────────────────────────────────────────────────
import type { ProductionTemplate } from '../types';

// ─── BLACK SOLDIER FLY (BSF) ─────────────────────────────────────────────────
export const bsfTemplate: ProductionTemplate = {
  id: 'bsf-larvae',
  name: 'Black Soldier Fly (BSF)',
  shortName: 'BSF',
  category: 'insects',
  species: 'Hermetia illucens',
  purpose: 'Larvae for Feed & Organic Waste Bioconversion',
  description:
    'BSF larvae convert organic waste into high-protein animal feed. A closed loop: eggs → larvae → frass → prepupae harvest.',
  icon: '🪲',
  color: '#1c1917',
  tags: ['bsf', 'insect farming', 'bioconversion', 'protein feed', 'frass', 'circular'],
  materials: [
    { id: 'bsf-colony', name: 'BSF Breeding Colony / Eggs', unit: 'count', category: 'input' },
    { id: 'organic-waste', name: 'Organic Waste / Food Scraps', unit: 'kg', category: 'input' },
    { id: 'bsf-larvae-out', name: 'Fresh BSF Larvae (BSFL)', unit: 'kg', category: 'output' },
    { id: 'dried-larvae', name: 'Dried BSF Larvae', unit: 'kg', category: 'output' },
    { id: 'bsf-frass', name: 'Frass (Organic Fertiliser)', unit: 'kg', category: 'output' },
    { id: 'bsf-oil', name: 'Larvae Oil (extracted)', unit: 'litre', category: 'output' },
  ],
  kpis: [
    { id: 'fcr', name: 'Feed Conversion Ratio (waste:larvae)', unit: 'ratio', goodDirection: 'down', benchmark: 5 },
    { id: 'larvae-protein', name: 'Larvae Protein Content', unit: 'percent', goodDirection: 'up', benchmark: 42 },
    { id: 'cycle-time', name: 'Larval Cycle Duration', unit: 'day', goodDirection: 'down', benchmark: 14 },
    { id: 'yield-kg', name: 'Fresh Larvae per kg Waste', unit: 'ratio', goodDirection: 'up', benchmark: 0.18 },
  ],
  stages: [
    {
      id: 'colony-breeding',
      name: 'Breeding Colony Management',
      description: 'Maintain adult fly colony for continuous egg supply',
      typicalDurationDays: 21,
      color: '#57534e',
      inputs: [
        { id: 'cage', label: 'Adult Fly Cage', unit: 'count', required: true },
        { id: 'egg-substrate', label: 'Egg-Laying Substrate (corrugated card/wood)', unit: 'count', required: true },
      ],
      activities: [
        'Maintain adult cage temperature 27–30°C, 60–80% humidity',
        'Provide sugar water and water pads for adults',
        'Collect egg clutches every 2–3 days',
        'Monitor adult fly numbers — replenish from prepupae every 4 weeks',
      ],
      measurements: [
        { id: 'eggs-collected', name: 'Egg Clutches Collected', unit: 'count', frequency: 'daily', required: true },
        { id: 'adult-count', name: 'Adult Fly Estimated Count', unit: 'count', frequency: 'weekly', required: false },
        { id: 'temp', name: 'Colony Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 27, max: 30 } },
      ],
      outputs: [],
      possibleNextStages: ['incubation'],
    },
    {
      id: 'incubation',
      name: 'Egg Incubation',
      description: 'Eggs hatch to neonates in 3–4 days at optimal conditions',
      typicalDurationDays: 4,
      color: '#a8a29e',
      inputs: [
        { id: 'egg-clutch', label: 'Egg Clutches', unit: 'count', required: true },
        { id: 'hatch-substrate', label: 'Hatch Substrate (wheat bran, chicken mash)', unit: 'kg', required: true },
      ],
      activities: [
        'Place egg clutches on moist hatch substrate at 28°C',
        'Maintain 80% humidity — mist if needed',
        'Check hatch after 72 hours',
        'Transfer neonates to waste bins once active',
      ],
      measurements: [
        { id: 'hatch-rate', name: 'Hatch Rate', unit: 'percent', frequency: 'per_event', required: true, benchmark: { target: 90 } },
        { id: 'hatch-temp', name: 'Incubation Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 27, max: 30 } },
      ],
      outputs: [],
      possibleNextStages: ['larvae-grow-out'],
    },
    {
      id: 'larvae-grow-out',
      name: 'Larval Grow-Out & Waste Bioconversion',
      description: 'Larvae eat organic waste intensively over 10–14 days',
      typicalDurationDays: 14,
      color: '#78716c',
      inputs: [
        { id: 'waste-feed', label: 'Organic Waste (food scraps, manure, market waste)', unit: 'kg', required: true },
        { id: 'bins', label: 'Growing Bins / Trays', unit: 'count', required: true },
      ],
      activities: [
        'Feed larvae 100–200 g waste per 1,000 larvae daily',
        'Keep substrate moist (60–70% moisture)',
        'Monitor larvae growth — check size every 3 days',
        'Maintain temperature 27–30°C for fastest growth',
        'Aerate bins to reduce ammonia build-up',
      ],
      measurements: [
        { id: 'waste-consumed', name: 'Waste Consumed', unit: 'kg', frequency: 'daily', required: true },
        { id: 'larvae-weight', name: 'Average Larvae Weight', unit: 'g', frequency: 'weekly', required: true, benchmark: { target: 0.2 } },
        { id: 'temp-bin', name: 'Bin Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 25, max: 30 } },
        { id: 'moisture', name: 'Substrate Moisture', unit: 'percent', frequency: 'daily', required: false, benchmark: { min: 60, max: 70 } },
      ],
      outputs: [],
      possibleNextStages: ['harvest-process'],
    },
    {
      id: 'harvest-process',
      name: 'Harvest & Processing',
      description: 'Separate prepupae from frass; dry or use fresh',
      typicalDurationDays: 3,
      color: '#a16207',
      inputs: [],
      activities: [
        'Use self-harvesting ramp: prepupae crawl up and collect themselves',
        'Or sieve larvae from frass manually',
        'Weigh fresh larvae yield',
        'Rinse larvae with water before use/sale',
        'Blanch/dry at 60°C if selling dried product',
        'Collect frass — dry and bag as organic fertiliser',
        'Return some prepupae to breeding colony',
      ],
      measurements: [
        { id: 'fresh-larvae-kg', name: 'Fresh Larvae Harvested', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'dried-larvae-kg', name: 'Dried Larvae (if processed)', unit: 'kg', frequency: 'per_event', required: false },
        { id: 'frass-kg', name: 'Frass Collected', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'waste-reduction', name: 'Waste Reduction', unit: 'percent', frequency: 'per_event', required: false, benchmark: { target: 70 } },
      ],
      outputs: [
        { id: 'bsf-larvae-out', label: 'Fresh BSF Larvae', unit: 'kg', routingOptions: ['sale', 'processing', 'own_use'] },
        { id: 'dried-larvae', label: 'Dried Larvae', unit: 'kg', routingOptions: ['sale', 'inventory'] },
        { id: 'bsf-frass', label: 'Frass Fertiliser', unit: 'kg', routingOptions: ['sale', 'own_use', 'inventory'] },
      ],
      possibleNextStages: ['colony-breeding'],
    },
  ],
};

// ─── CRICKET FARMING ─────────────────────────────────────────────────────────
export const cricketFarmingTemplate: ProductionTemplate = {
  id: 'cricket-farming',
  name: 'Cricket Farming',
  shortName: 'Crickets',
  category: 'insects',
  species: 'Acheta domesticus / Gryllus bimaculatus',
  purpose: 'Human Food & Animal Feed',
  description:
    'Batch cricket production for human consumption (flour, whole roasted) or animal feed. High protein, low footprint.',
  icon: '🦗',
  color: '#65a30d',
  tags: ['cricket', 'insect protein', 'edible insects', 'entomophagy', 'feed', 'food'],
  materials: [
    { id: 'cricket-colony', name: 'Breeding Stock (adult crickets)', unit: 'count', category: 'input' },
    { id: 'cricket-feed', name: 'Cricket Feed (grain bran, vegetable scraps)', unit: 'kg', category: 'input' },
    { id: 'egg-tray-sub', name: 'Egg-Laying Substrate (moist sand/coir)', unit: 'kg', category: 'input' },
    { id: 'fresh-crickets', name: 'Live / Fresh Crickets', unit: 'kg', category: 'output' },
    { id: 'roasted-crickets', name: 'Roasted Whole Crickets', unit: 'kg', category: 'output' },
    { id: 'cricket-flour', name: 'Cricket Flour / Powder', unit: 'kg', category: 'output' },
    { id: 'cricket-frass', name: 'Cricket Frass (fertiliser)', unit: 'kg', category: 'output' },
  ],
  kpis: [
    { id: 'fcr-cricket', name: 'Feed Conversion Ratio', unit: 'ratio', goodDirection: 'down', benchmark: 2.1 },
    { id: 'cycle-days', name: 'Production Cycle (egg→adult)', unit: 'day', goodDirection: 'down', benchmark: 45 },
    { id: 'survival-rate', name: 'Survival Rate Egg→Harvest', unit: 'percent', goodDirection: 'up', benchmark: 70 },
    { id: 'protein-pct', name: 'Protein Content (dry weight)', unit: 'percent', goodDirection: 'up', benchmark: 65 },
  ],
  stages: [
    {
      id: 'egg-laying',
      name: 'Egg Production & Laying',
      typicalDurationDays: 7,
      color: '#fef9c3',
      inputs: [
        { id: 'adults', label: 'Adult Breeding Crickets (male + female)', unit: 'count', required: true },
        { id: 'sub', label: 'Moist Egg-Laying Substrate', unit: 'kg', required: true },
      ],
      activities: [
        'Place adults in breeding boxes at ratio 1:3 male:female',
        'Provide moist substrate (coir/sand) for egg laying',
        'Maintain 28–32°C, 60–80% humidity',
        'Collect egg-laden substrate every 5–7 days',
      ],
      measurements: [
        { id: 'eggs-subs', name: 'Egg Substrate Batches Collected', unit: 'count', frequency: 'weekly', required: true },
        { id: 'breed-temp', name: 'Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 28, max: 32 } },
      ],
      outputs: [],
      possibleNextStages: ['incubation'],
    },
    {
      id: 'incubation',
      name: 'Incubation',
      typicalDurationDays: 10,
      color: '#d9f99d',
      inputs: [{ id: 'egg-sub', label: 'Collected Egg Substrate', unit: 'kg', required: true }],
      activities: [
        'Keep substrate moist at 28–30°C',
        'Nymphs hatch in 8–12 days',
        'Transfer nymphs to growing boxes once mobile',
      ],
      measurements: [
        { id: 'hatch-rate', name: 'Hatch Rate', unit: 'percent', frequency: 'per_event', required: true, benchmark: { target: 80 } },
        { id: 'inc-temp', name: 'Incubation Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 28, max: 30 } },
      ],
      outputs: [],
      possibleNextStages: ['nymph-grow'],
    },
    {
      id: 'nymph-grow',
      name: 'Nymph & Juvenile Grow-Out',
      typicalDurationDays: 28,
      color: '#86efac',
      inputs: [
        { id: 'feed', label: 'Dry Grain / Bran / Vegetable Scraps', unit: 'kg', required: true },
        { id: 'water-gel', label: 'Water Gel / Fresh Vegetables (moisture source)', unit: 'kg', required: true },
      ],
      activities: [
        'Feed ad libitum twice daily',
        'Provide water gel or fresh vegetables — crickets drown in open water',
        'Provide egg-tray structures for hiding',
        'Maintain 28–32°C, 50–70% humidity',
        'Clean boxes weekly — remove frass',
        'Separate size classes if density too high',
      ],
      measurements: [
        { id: 'cricket-weight', name: 'Average Cricket Weight', unit: 'g', frequency: 'weekly', required: true, benchmark: { target: 1.2 } },
        { id: 'feed-consumed', name: 'Feed Consumed', unit: 'kg', frequency: 'weekly', required: true },
        { id: 'mortality', name: 'Mortality Count', unit: 'count', frequency: 'weekly', required: false },
        { id: 'temp', name: 'Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 28, max: 32 } },
      ],
      outputs: [],
      possibleNextStages: ['harvest'],
    },
    {
      id: 'harvest',
      name: 'Harvest & Processing',
      typicalDurationDays: 2,
      color: '#4ade80',
      inputs: [],
      activities: [
        'Withhold feed for 24h (gut-purge) before harvest',
        'Chill crickets in freezer (0°C) for 30 min — humane kill',
        'Weigh total harvest',
        'Rinse in clean water',
        'Blanch or oven-toast at 180°C for 15 min if selling fresh-roasted',
        'Or freeze-dry / grind to flour',
        'Collect frass from boxes — bag as fertiliser',
      ],
      measurements: [
        { id: 'harvest-kg', name: 'Fresh Cricket Yield', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'flour-kg', name: 'Cricket Flour Produced', unit: 'kg', frequency: 'per_event', required: false },
        { id: 'fcr-actual', name: 'Actual FCR', unit: 'ratio', frequency: 'per_event', required: true },
        { id: 'frass-kg', name: 'Frass Collected', unit: 'kg', frequency: 'per_event', required: false },
      ],
      outputs: [
        { id: 'fresh-crickets', label: 'Live / Fresh Crickets', unit: 'kg', routingOptions: ['sale', 'processing', 'own_use'] },
        { id: 'roasted-crickets', label: 'Roasted Whole Crickets', unit: 'kg', routingOptions: ['sale', 'inventory'] },
        { id: 'cricket-flour', label: 'Cricket Flour', unit: 'kg', routingOptions: ['sale', 'processing', 'inventory'] },
        { id: 'cricket-frass', label: 'Frass Fertiliser', unit: 'kg', routingOptions: ['sale', 'own_use'] },
      ],
      possibleNextStages: ['egg-laying'],
    },
  ],
};

// ─── MEALWORM FARMING ────────────────────────────────────────────────────────
export const mealwormTemplate: ProductionTemplate = {
  id: 'mealworm-farming',
  name: 'Mealworm Farming',
  shortName: 'Mealworms',
  category: 'insects',
  species: 'Tenebrio molitor',
  purpose: 'Feed Ingredient & Human Protein',
  description:
    'Mealworm beetle larvae are a high-protein feed additive for poultry, fish, and humans. Continuous multi-tray production.',
  icon: '🐛',
  color: '#a16207',
  tags: ['mealworm', 'Tenebrio', 'insect protein', 'feed', 'beetle larvae', 'edible insect'],
  materials: [
    { id: 'beetle-colony', name: 'Darkling Beetle Colony', unit: 'count', category: 'input' },
    { id: 'mealworm-feed', name: 'Bran / Oat / Grain Feed', unit: 'kg', category: 'input' },
    { id: 'mw-fresh', name: 'Fresh Mealworms (larvae)', unit: 'kg', category: 'output' },
    { id: 'mw-dried', name: 'Dried Mealworms', unit: 'kg', category: 'output' },
    { id: 'mw-flour', name: 'Mealworm Flour', unit: 'kg', category: 'output' },
    { id: 'mw-frass', name: 'Mealworm Frass', unit: 'kg', category: 'output' },
  ],
  kpis: [
    { id: 'fcr-mw', name: 'Feed Conversion Ratio', unit: 'ratio', goodDirection: 'down', benchmark: 2.5 },
    { id: 'cycle-weeks', name: 'Larval Stage Duration', unit: 'day', goodDirection: 'down', benchmark: 70 },
    { id: 'protein-pct', name: 'Protein (dry weight)', unit: 'percent', goodDirection: 'up', benchmark: 52 },
    { id: 'mortality-mw', name: 'Larval Mortality Rate', unit: 'percent', goodDirection: 'down', benchmark: 5 },
  ],
  stages: [
    {
      id: 'beetle-colony',
      name: 'Beetle Colony (Egg Laying)',
      typicalDurationDays: 30,
      color: '#fef3c7',
      inputs: [
        { id: 'adults', label: 'Adult Darkling Beetles', unit: 'count', required: true },
        { id: 'bran', label: 'Wheat Bran Substrate', unit: 'kg', required: true },
      ],
      activities: [
        'Keep beetles in shallow trays with 5 cm bran substrate',
        'Maintain 25–28°C',
        'Provide moisture via carrot slices, apple, potato pieces',
        'Sieve trays every 2 weeks — eggs fall through 1.5 mm mesh',
        'Collect egg-containing bran below sieve',
      ],
      measurements: [
        { id: 'beetle-count', name: 'Active Beetle Count', unit: 'count', frequency: 'monthly', required: false },
        { id: 'egg-trays', name: 'Egg Trays Collected', unit: 'count', frequency: 'weekly', required: true },
        { id: 'temp-beetle', name: 'Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 25, max: 28 } },
      ],
      outputs: [],
      possibleNextStages: ['larvae-grow'],
    },
    {
      id: 'larvae-grow',
      name: 'Larval Grow-Out (8–12 Weeks)',
      typicalDurationDays: 70,
      color: '#fde68a',
      inputs: [
        { id: 'bran-feed', label: 'Wheat Bran / Oat Feed', unit: 'kg', required: true },
        { id: 'moisture', label: 'Moisture Vegetables (carrot, potato)', unit: 'kg', required: true },
      ],
      activities: [
        'Transfer egg bran to grow-out trays',
        'Add bran and top up as consumed',
        'Provide fresh moisture vegetables 2–3× per week',
        'Maintain 25–28°C — temperature drives growth rate',
        'Sieve frass from bran every 2 weeks',
        'Grade larvae by size (optional) for uniform harvest',
      ],
      measurements: [
        { id: 'larva-length', name: 'Average Larva Length', unit: 'g', frequency: 'weekly', required: true, benchmark: { target: 25 } },
        { id: 'bran-used', name: 'Bran Consumed', unit: 'kg', frequency: 'weekly', required: true },
        { id: 'temp', name: 'Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 25, max: 28 } },
        { id: 'mortality', name: 'Mortality Estimate', unit: 'percent', frequency: 'weekly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['harvest-mw', 'pupation'],
    },
    {
      id: 'pupation',
      name: 'Pupation (Return to Beetle Colony)',
      typicalDurationDays: 21,
      color: '#d9f99d',
      inputs: [],
      activities: [
        'Collect pupae from grow-out trays (they stop moving)',
        'Place pupae in fresh bran in beetle emergence trays',
        'Pupae become adults in 14–21 days',
        'Transfer adults to beetle colony trays',
      ],
      measurements: [
        { id: 'pupae-count', name: 'Pupae Collected', unit: 'count', frequency: 'per_event', required: false },
        { id: 'emergence-rate', name: 'Adult Emergence Rate', unit: 'percent', frequency: 'per_event', required: false },
      ],
      outputs: [],
      possibleNextStages: ['beetle-colony'],
    },
    {
      id: 'harvest-mw',
      name: 'Harvest & Processing',
      typicalDurationDays: 2,
      color: '#a16207',
      inputs: [],
      activities: [
        'Sieve larvae from bran substrate (1.5 mm mesh)',
        'Gut-purge 24h on clean bran',
        'Freeze at -20°C for 24h (humane kill, also extends shelf life)',
        'Dry at 60°C for 4–6 hours or freeze-dry',
        'Pack in sealed bags with oxygen absorbers',
      ],
      measurements: [
        { id: 'fresh-yield', name: 'Fresh Larvae Yield', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'dried-yield', name: 'Dried Larvae Yield', unit: 'kg', frequency: 'per_event', required: false },
        { id: 'moisture-pct', name: 'Moisture Content (dried)', unit: 'percent', frequency: 'per_event', required: false, benchmark: { max: 8 } },
      ],
      outputs: [
        { id: 'mw-fresh', label: 'Fresh Mealworms', unit: 'kg', routingOptions: ['sale', 'own_use', 'processing'] },
        { id: 'mw-dried', label: 'Dried Mealworms', unit: 'kg', routingOptions: ['sale', 'inventory'] },
        { id: 'mw-frass', label: 'Mealworm Frass', unit: 'kg', routingOptions: ['sale', 'own_use'] },
      ],
      possibleNextStages: ['larvae-grow'],
    },
  ],
};

// ─── SILKWORM / SERICULTURE ───────────────────────────────────────────────────
export const silkwormTemplate: ProductionTemplate = {
  id: 'silkworm-sericulture',
  name: 'Silkworm (Sericulture)',
  shortName: 'Sericulture',
  category: 'insects',
  species: 'Bombyx mori',
  purpose: 'Raw Silk & Pupae',
  description:
    'Commercial silkworm rearing for raw silk thread. Dependent on mulberry leaves. 5 larval instars → cocooning → reeling.',
  icon: '🧵',
  color: '#f0abfc',
  tags: ['silkworm', 'sericulture', 'silk', 'Bombyx mori', 'mulberry', 'reeling'],
  materials: [
    { id: 'silkworm-eggs', name: 'Silkworm Eggs (DFLs)', unit: 'count', category: 'input' },
    { id: 'mulberry', name: 'Mulberry Leaves', unit: 'kg', category: 'input' },
    { id: 'silk-cocoon', name: 'Silk Cocoons (fresh)', unit: 'kg', category: 'output' },
    { id: 'raw-silk', name: 'Raw Silk Thread (reeled)', unit: 'kg', category: 'output' },
    { id: 'silk-pupae', name: 'Silkworm Pupae (for food/feed)', unit: 'kg', category: 'output' },
    { id: 'seed-cocoon', name: 'Seed Cocoons (breeding)', unit: 'count', category: 'output' },
  ],
  kpis: [
    { id: 'cocoon-dfls', name: 'Cocoon Yield per DFL', unit: 'kg', goodDirection: 'up', benchmark: 65 },
    { id: 'sr-ratio', name: 'Shell Ratio (silk %)', unit: 'percent', goodDirection: 'up', benchmark: 22 },
    { id: 'filament-length', name: 'Average Filament Length', unit: 'g', goodDirection: 'up', benchmark: 1200 },
    { id: 'crop-survival', name: 'Crop Survival Rate', unit: 'percent', goodDirection: 'up', benchmark: 85 },
  ],
  stages: [
    {
      id: 'egg-hatching',
      name: 'Egg Incubation & Hatching',
      typicalDurationDays: 10,
      color: '#fce7f3',
      inputs: [
        { id: 'dfls', label: 'Disease-Free Layings (DFLs)', unit: 'count', required: true },
      ],
      activities: [
        'Incubate eggs at 25°C, 75–80% humidity in dark',
        'Expose to light on day 9 to synchronise hatching',
        'Collect newly hatched larvae (black ants stage) on tender mulberry leaves',
      ],
      measurements: [
        { id: 'hatch-rate', name: 'Hatch Rate', unit: 'percent', frequency: 'per_event', required: true, benchmark: { target: 95 } },
        { id: 'inc-temp', name: 'Incubation Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 24, max: 26 } },
      ],
      outputs: [],
      possibleNextStages: ['early-instars'],
    },
    {
      id: 'early-instars',
      name: 'Early Instars (I–III) — Young Age Rearing',
      typicalDurationDays: 12,
      color: '#e9d5ff',
      inputs: [
        { id: 'tender-mul', label: 'Tender Mulberry Leaves (young shoots)', unit: 'kg', required: true },
      ],
      activities: [
        'Feed tender mulberry 3× daily chopped finely',
        'Maintain 26–28°C, 85–90% humidity',
        'Bed-net and disinfect rearing trays between moults',
        'Remove dead larvae immediately',
        'Spread larvae to prevent overcrowding after each moult',
      ],
      measurements: [
        { id: 'leaf-consumed', name: 'Mulberry Consumed', unit: 'kg', frequency: 'daily', required: true },
        { id: 'larvae-count', name: 'Live Larvae Count', unit: 'count', frequency: 'per_event', required: true },
        { id: 'temp-yr', name: 'Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 26, max: 28 } },
      ],
      outputs: [],
      possibleNextStages: ['late-instars'],
    },
    {
      id: 'late-instars',
      name: 'Late Instars (IV–V) — Late Age Rearing',
      typicalDurationDays: 12,
      color: '#c4b5fd',
      inputs: [
        { id: 'mature-mul', label: 'Mature Mulberry Leaves (whole leaves)', unit: 'kg', required: true },
      ],
      activities: [
        'Feed whole mature leaves 3–4× daily (large appetite)',
        'Larvae consume 80% of total leaf in this stage',
        'Reduce temperature to 24–26°C',
        'Watch for spinning behaviour (yellow body, reduced movement)',
        'Prepare mountages (bamboo/spirals) when larvae start spinning',
      ],
      measurements: [
        { id: 'leaf-v', name: 'Mulberry Consumed (Instar V)', unit: 'kg', frequency: 'daily', required: true },
        { id: 'larval-weight', name: 'Mature Larva Weight', unit: 'g', frequency: 'per_event', required: false, benchmark: { target: 4.5 } },
        { id: 'spin-start', name: 'Spinning Larvae %', unit: 'percent', frequency: 'daily', required: true },
      ],
      outputs: [],
      possibleNextStages: ['cocooning'],
    },
    {
      id: 'cocooning',
      name: 'Mounting & Cocooning',
      typicalDurationDays: 5,
      color: '#a78bfa',
      inputs: [
        { id: 'mountage', label: 'Mountages (bamboo/rotating)', unit: 'count', required: true },
      ],
      activities: [
        'Transfer mature larvae to mountages',
        'Maintain 24°C, 65% humidity during spinning',
        'Larvae spin cocoon in 2–3 days',
        'Leave undisturbed for 5–6 days after spinning',
      ],
      measurements: [
        { id: 'cocoon-count', name: 'Cocoons Formed', unit: 'count', frequency: 'per_event', required: true },
        { id: 'defect-pct', name: 'Defective Cocoon %', unit: 'percent', frequency: 'per_event', required: true, benchmark: { max: 5 } },
      ],
      outputs: [],
      possibleNextStages: ['harvest-reeling'],
    },
    {
      id: 'harvest-reeling',
      name: 'Cocoon Harvest & Reeling',
      typicalDurationDays: 3,
      color: '#7c3aed',
      inputs: [
        { id: 'hot-water', label: 'Hot Water (80–90°C) for softening sericin', unit: 'litre', required: true },
      ],
      activities: [
        'Pick cocoons from mountages 5–6 days after spinning',
        'Grade cocoons: A (reelable), B (doubled), C (defective)',
        'Kill pupae with hot air (80°C) or steam if not reeling same day',
        'Soften cocoons in 80°C water to dissolve sericin',
        'Reel silk on motorised or hand-reel at 120 m/min',
        'Weigh and record raw silk thread',
        'Collect pupae from stifled cocoons — high protein animal feed',
      ],
      measurements: [
        { id: 'cocoon-kg', name: 'Fresh Cocoon Weight', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'silk-kg', name: 'Raw Silk Thread Reeled', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'shell-ratio', name: 'Shell Ratio', unit: 'percent', frequency: 'per_event', required: true, benchmark: { target: 22 } },
        { id: 'pupae-kg', name: 'Pupae Weight', unit: 'kg', frequency: 'per_event', required: false },
      ],
      outputs: [
        { id: 'silk-cocoon', label: 'Silk Cocoons (fresh)', unit: 'kg', routingOptions: ['sale', 'processing'] },
        { id: 'raw-silk', label: 'Raw Silk Thread', unit: 'kg', routingOptions: ['sale', 'inventory'] },
        { id: 'silk-pupae', label: 'Silkworm Pupae', unit: 'kg', routingOptions: ['sale', 'own_use', 'processing'] },
      ],
      possibleNextStages: ['egg-hatching'],
    },
  ],
};

// ─── VERMICULTURE (EARTHWORMS) ───────────────────────────────────────────────
export const vermicultureTemplate: ProductionTemplate = {
  id: 'vermiculture',
  name: 'Vermiculture (Earthworms)',
  shortName: 'Vermiculture',
  category: 'insects',
  species: 'Eisenia fetida / Lumbricus rubellus',
  purpose: 'Vermicompost & Worm Biomass',
  description:
    'Continuous worm composting converts organic waste into premium vermicompost and worm protein biomass. Operates year-round.',
  icon: '🪱',
  color: '#92400e',
  tags: ['vermiculture', 'vermicompost', 'earthworm', 'Eisenia fetida', 'organic waste', 'fertiliser'],
  materials: [
    { id: 'worm-stock', name: 'Worm Starter Stock (worms + cocoons)', unit: 'kg', category: 'input' },
    { id: 'organic-input', name: 'Organic Waste / Manure / Bedding', unit: 'kg', category: 'input' },
    { id: 'vermicompost', name: 'Vermicompost (castings)', unit: 'kg', category: 'output' },
    { id: 'worm-biomass', name: 'Harvested Worms (fresh weight)', unit: 'kg', category: 'output' },
    { id: 'worm-tea', name: 'Worm Leachate (liquid fertiliser)', unit: 'litre', category: 'output' },
  ],
  kpis: [
    { id: 'worm-dbl', name: 'Population Doubling Time', unit: 'day', goodDirection: 'down', benchmark: 60 },
    { id: 'compost-ratio', name: 'Compost Conversion Ratio', unit: 'ratio', goodDirection: 'up', benchmark: 0.5 },
    { id: 'worm-yield', name: 'Worm Biomass Yield / Bed / Month', unit: 'kg', goodDirection: 'up', benchmark: 3 },
    { id: 'moisture', name: 'Bed Moisture', unit: 'percent', goodDirection: 'neutral', benchmark: 70 },
  ],
  stages: [
    {
      id: 'bed-setup',
      name: 'Bed Set-Up & Inoculation',
      typicalDurationDays: 14,
      color: '#fef3c7',
      inputs: [
        { id: 'bedding', label: 'Bedding (coir, straw, shredded paper)', unit: 'kg', required: true },
        { id: 'worms', label: 'Worm Stock (Eisenia fetida)', unit: 'kg', required: true },
        { id: 'pre-compost', label: 'Pre-composted Organic Feed', unit: 'kg', required: true },
      ],
      activities: [
        'Prepare beds/windrows 60 cm wide × 30 cm deep',
        'Soak bedding to 60–70% moisture',
        'Add pre-composted feed layer (avoid fresh manure — too hot)',
        'Introduce worms at 1–2 kg/m² of bed',
        'Cover with burlap to retain moisture',
        'Monitor pH: keep between 6.5 and 7.5',
      ],
      measurements: [
        { id: 'bed-temp', name: 'Bed Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 20, max: 28 } },
        { id: 'bed-moisture', name: 'Bed Moisture', unit: 'percent', frequency: 'daily', required: true, benchmark: { min: 60, max: 80 } },
        { id: 'worm-inoculated', name: 'Worm Stock Inoculated', unit: 'kg', frequency: 'per_event', required: true },
      ],
      outputs: [],
      possibleNextStages: ['continuous-production'],
    },
    {
      id: 'continuous-production',
      name: 'Continuous Feeding & Production',
      typicalDurationDays: 90,
      color: '#a16207',
      inputs: [
        { id: 'organic-feed', label: 'Organic Waste / Manure (pre-composted)', unit: 'kg', required: true },
        { id: 'water', label: 'Water (irrigation)', unit: 'litre', required: true },
      ],
      activities: [
        'Feed worms every 3–5 days — thin layer on top of bed',
        'Water bed twice daily if not raining (keep moist not waterlogged)',
        'Avoid feeding raw/fresh manure, citrus, onion, salty food',
        'Turn bed gently every 2 weeks to aerate',
        'Collect leachate from drainage and dilute 1:10 as liquid fertiliser',
        'Monitor worm activity: healthy worms active near surface',
      ],
      measurements: [
        { id: 'feed-added', name: 'Organic Waste Added', unit: 'kg', frequency: 'weekly', required: true },
        { id: 'leachate', name: 'Leachate Collected', unit: 'litre', frequency: 'weekly', required: false },
        { id: 'bed-temp', name: 'Bed Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 20, max: 28 } },
        { id: 'bed-moisture', name: 'Bed Moisture', unit: 'percent', frequency: 'daily', required: true, benchmark: { min: 60, max: 80 } },
        { id: 'worm-activity', name: 'Worm Activity (1=low, 5=high)', unit: 'ratio', frequency: 'weekly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['harvest-vermi'],
    },
    {
      id: 'harvest-vermi',
      name: 'Harvest (Worms + Vermicompost)',
      typicalDurationDays: 7,
      color: '#78350f',
      inputs: [],
      activities: [
        'Stop feeding 7–10 days before harvest to concentrate worms',
        'Shine bright light on bed — worms move down from top',
        'Scrape top layer of vermicompost (worm-free)',
        'Continue until most worms visible at bottom',
        'Separate worms from castings by hand or mechanical separator',
        'Weigh and package worms — sell or return portion to beds',
        'Cure vermicompost for 2 weeks before bagging',
        'Test vermicompost NPK if selling as certified product',
      ],
      measurements: [
        { id: 'vermicompost-kg', name: 'Vermicompost Harvested', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'worm-kg', name: 'Worm Biomass Harvested', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'leachate-harvest', name: 'Leachate Collected', unit: 'litre', frequency: 'per_event', required: false },
      ],
      outputs: [
        { id: 'vermicompost', label: 'Vermicompost (castings)', unit: 'kg', routingOptions: ['sale', 'own_use', 'inventory'] },
        { id: 'worm-biomass', label: 'Worm Biomass', unit: 'kg', routingOptions: ['sale', 'own_use', 'transfer'] },
        { id: 'worm-tea', label: 'Worm Leachate', unit: 'litre', routingOptions: ['sale', 'own_use'] },
      ],
      possibleNextStages: ['continuous-production'],
    },
  ],
};

// ─── SNAIL FARMING (HELICICULTURE) ───────────────────────────────────────────
export const snailFarmingTemplate: ProductionTemplate = {
  id: 'snail-heliciculture',
  name: 'Snail Farming (Heliciculture)',
  shortName: 'Snails',
  category: 'insects',
  species: 'Achatina fulica / Helix pomatia',
  purpose: 'Snail Meat & Cosmetics',
  description:
    'Giant African Land Snail or European snail farming for meat, slime (cosmetics), and shells. Semi-intensive to intensive systems.',
  icon: '🐌',
  color: '#78716c',
  tags: ['snail', 'heliciculture', 'Achatina', 'escargot', 'snail mucin', 'cosmetics', 'meat'],
  materials: [
    { id: 'snail-stock', name: 'Breeder Snails', unit: 'count', category: 'input' },
    { id: 'snail-feed', name: 'Snail Feed (leaves, fruit, concentrates)', unit: 'kg', category: 'input' },
    { id: 'calcium', name: 'Calcium Supplement (crushed oyster shell / limestone)', unit: 'kg', category: 'input' },
    { id: 'snail-meat', name: 'Snail Meat (fresh)', unit: 'kg', category: 'output' },
    { id: 'snail-mucin', name: 'Snail Slime / Mucin', unit: 'litre', category: 'output' },
    { id: 'snail-shell', name: 'Snail Shells', unit: 'kg', category: 'output' },
    { id: 'snail-eggs', name: 'Snail Eggs (for sale)', unit: 'count', category: 'output' },
  ],
  kpis: [
    { id: 'gwp', name: 'Average Daily Weight Gain', unit: 'g', goodDirection: 'up', benchmark: 0.5 },
    { id: 'fcr-snail', name: 'Feed Conversion Ratio', unit: 'ratio', goodDirection: 'down', benchmark: 5 },
    { id: 'harvest-weight', name: 'Average Harvest Weight', unit: 'g', goodDirection: 'up', benchmark: 200 },
    { id: 'survival', name: 'Survival Rate to Market', unit: 'percent', goodDirection: 'up', benchmark: 75 },
  ],
  stages: [
    {
      id: 'breeding',
      name: 'Breeding & Egg Laying',
      typicalDurationDays: 60,
      color: '#e7e5e4',
      inputs: [
        { id: 'breeders', label: 'Mature Breeder Snails (>6 months)', unit: 'count', required: true },
        { id: 'pen', label: 'Breeding Pen with Moist Soil Substrate', unit: 'count', required: true },
        { id: 'calcium-b', label: 'Calcium (for shell building)', unit: 'kg', required: true },
      ],
      activities: [
        'Place breeders at 10 snails per m² in breeding pen',
        'Keep substrate moist at 80% humidity (sprinkle twice daily in dry season)',
        'Maintain temperature 22–28°C',
        'Snails lay 100–400 eggs per clutch in soil 5 cm deep',
        'Collect egg clutches after 2 weeks and move to incubation box',
      ],
      measurements: [
        { id: 'eggs-clutch', name: 'Egg Clutches Found', unit: 'count', frequency: 'weekly', required: true },
        { id: 'eggs-per-clutch', name: 'Eggs per Clutch (average)', unit: 'count', frequency: 'per_event', required: false, benchmark: { target: 200 } },
        { id: 'humidity', name: 'Pen Humidity', unit: 'percent', frequency: 'daily', required: true, benchmark: { min: 75, max: 85 } },
        { id: 'pen-temp', name: 'Pen Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 22, max: 28 } },
      ],
      outputs: [],
      possibleNextStages: ['incubation-hatching'],
    },
    {
      id: 'incubation-hatching',
      name: 'Egg Incubation & Hatching',
      typicalDurationDays: 28,
      color: '#d6d3d1',
      inputs: [
        { id: 'egg-clutches', label: 'Egg Clutches', unit: 'count', required: true },
        { id: 'hatch-box', label: 'Hatching Box with Moist Soil', unit: 'count', required: true },
      ],
      activities: [
        'Place clutches in moist (not wet) potting soil 2 cm deep',
        'Cover box with ventilated lid',
        'Maintain 27–29°C, 80% humidity',
        'Eggs hatch in 21–28 days',
        'Transfer hatchlings to nursery pen after 48h',
      ],
      measurements: [
        { id: 'hatch-rate', name: 'Hatch Rate', unit: 'percent', frequency: 'per_event', required: true, benchmark: { target: 70 } },
        { id: 'hatch-temp', name: 'Hatch Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 27, max: 29 } },
      ],
      outputs: [],
      possibleNextStages: ['nursery'],
    },
    {
      id: 'nursery',
      name: 'Nursery (Hatchlings to Juveniles)',
      typicalDurationDays: 60,
      color: '#a8a29e',
      inputs: [
        { id: 'leafy-veg', label: 'Tender Greens (pawpaw, taro, cabbage)', unit: 'kg', required: true },
        { id: 'calcium-n', label: 'Calcium Supplement', unit: 'kg', required: true },
      ],
      activities: [
        'Keep hatchlings at 200/m² max density in nursery',
        'Feed tender leaves and mashed fruit daily',
        'Provide calcium (crushed limestone/shell) at all times',
        'Keep floor moist with water mist twice daily',
        'Clean pen twice weekly — remove droppings and uneaten food',
      ],
      measurements: [
        { id: 'avg-weight', name: 'Average Snail Weight', unit: 'g', frequency: 'weekly', required: true, benchmark: { target: 20 } },
        { id: 'mortality', name: 'Mortality Count', unit: 'count', frequency: 'weekly', required: true },
        { id: 'feed-consumed', name: 'Feed Consumed', unit: 'kg', frequency: 'weekly', required: true },
      ],
      outputs: [],
      possibleNextStages: ['grow-out'],
    },
    {
      id: 'grow-out',
      name: 'Grow-Out to Market Weight',
      typicalDurationDays: 150,
      color: '#78716c',
      inputs: [
        { id: 'green-feed', label: 'Green Leaves / Fruit / Concentrates', unit: 'kg', required: true },
        { id: 'calcium-go', label: 'Calcium', unit: 'kg', required: true },
        { id: 'water-mist', label: 'Water (misting)', unit: 'litre', required: true },
      ],
      activities: [
        'Transfer to grow-out pens at 50 snails/m²',
        'Feed in the evening (snails most active at night)',
        'Provide calcium ad libitum for strong shells',
        'Increase ventilation in hot dry weather',
        'Weed out snails with cracked or deformed shells',
        'Grade snails at 3 months — separate sizes for uniform harvest',
      ],
      measurements: [
        { id: 'avg-weight-go', name: 'Average Weight', unit: 'g', frequency: 'monthly', required: true, benchmark: { target: 200 } },
        { id: 'fcr', name: 'FCR (feed:weight gain)', unit: 'ratio', frequency: 'monthly', required: true, benchmark: { max: 5 } },
        { id: 'density', name: 'Stocking Density', unit: 'count', frequency: 'monthly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['harvest-snail'],
    },
    {
      id: 'harvest-snail',
      name: 'Harvest & Processing',
      typicalDurationDays: 7,
      color: '#44403c',
      inputs: [],
      activities: [
        'Withhold food for 3–5 days (purging)',
        'Collect snails weighing >200 g',
        'Kill humanely: plunge in boiling water 5 min or salt brine',
        'Extract meat from shell using knife',
        'Weigh dressed meat separately from shells',
        'Pack in ice for fresh market or blanch + freeze',
        'Collect slime (mucin) if market exists — handle live snails gently',
      ],
      measurements: [
        { id: 'snails-harvested', name: 'Snails Harvested', unit: 'count', frequency: 'per_event', required: true },
        { id: 'live-weight', name: 'Total Live Weight', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'dressed-weight', name: 'Dressed Meat Weight', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'dressing-pct', name: 'Dressing Percentage', unit: 'percent', frequency: 'per_event', required: false, benchmark: { target: 40 } },
        { id: 'shell-kg', name: 'Shell Weight (if sold)', unit: 'kg', frequency: 'per_event', required: false },
      ],
      outputs: [
        { id: 'snail-meat', label: 'Snail Meat (fresh)', unit: 'kg', routingOptions: ['sale', 'inventory', 'processing'] },
        { id: 'snail-shell', label: 'Shells', unit: 'kg', routingOptions: ['sale', 'own_use', 'waste'] },
        { id: 'snail-mucin', label: 'Snail Mucin (slime)', unit: 'litre', routingOptions: ['sale', 'processing'] },
      ],
      possibleNextStages: ['breeding'],
    },
  ],
};

// ─── STINGLESS BEE (MELIPONICULTURE) ─────────────────────────────────────────
export const stinglessBeeTemplate: ProductionTemplate = {
  id: 'stingless-bee',
  name: 'Stingless Bee (Meliponiculture)',
  shortName: 'Stingless Bee',
  category: 'insects',
  species: 'Meliponini spp. (Trigona, Melipona, Dactylurina)',
  purpose: 'Honey, Propolis & Pollination',
  description:
    'Stingless bee keeping for premium medicinal honey, cerumen, and pollination services. Safe, low-input, ideal for peri-urban.',
  icon: '🐝',
  color: '#b45309',
  tags: ['stingless bee', 'meliponiculture', 'honey', 'propolis', 'Trigona', 'Melipona', 'pollination'],
  materials: [
    { id: 'colony-box', name: 'Colony Box with Colony', unit: 'count', category: 'input' },
    { id: 'sugar-water', label: 'Sugar Water Supplement', unit: 'kg', category: 'input' },
    { id: 'stingless-honey', name: 'Stingless Bee Honey', unit: 'litre', category: 'output' },
    { id: 'cerumen', name: 'Cerumen (propolis-wax mix)', unit: 'g', category: 'output' },
    { id: 'daughter-colony', name: 'Daughter Colony (for sale)', unit: 'count', category: 'output' },
  ],
  kpis: [
    { id: 'honey-yield', name: 'Honey Yield per Colony per Year', unit: 'litre', goodDirection: 'up', benchmark: 2 },
    { id: 'colony-growth', name: 'Colony Division Rate', unit: 'count', goodDirection: 'up', benchmark: 1 },
    { id: 'price-premium', name: 'Honey Price Premium vs Honeybee', unit: 'ratio', goodDirection: 'up', benchmark: 5 },
  ],
  stages: [
    {
      id: 'colony-setup',
      name: 'Colony Acquisition & Setup',
      typicalDurationDays: 30,
      color: '#fef3c7',
      inputs: [
        { id: 'colony', label: 'Stingless Bee Colony (in box)', unit: 'count', required: true },
      ],
      activities: [
        'Mount colony box in sheltered location, entrance facing East',
        'Protect from ants: apply Vaseline to support poles',
        'Seal any gaps with wax/cerumen — bees will do remaining sealing',
        'Monitor entrance activity daily for first 2 weeks',
        'Do not disturb colony for first 4 weeks',
      ],
      measurements: [
        { id: 'entrance-activity', name: 'Entrance Activity (low/medium/high)', unit: 'count', frequency: 'weekly', required: true },
      ],
      outputs: [],
      possibleNextStages: ['colony-management'],
    },
    {
      id: 'colony-management',
      name: 'Colony Management (Year-Round)',
      typicalDurationDays: 365,
      color: '#fbbf24',
      inputs: [
        { id: 'suppl', label: 'Sugar Water Supplement (scarcity period)', unit: 'kg', required: false },
      ],
      activities: [
        'Open hive once monthly for inspection — quick, gentle',
        'Check honey pots, brood area, queen activity',
        'Supplement feed during dry/dearth season',
        'Control ant, wax moth, and hive beetle',
        'Expand box if colony outgrows — add super',
        'Mark colony split candidates when population peaks',
      ],
      measurements: [
        { id: 'honey-pots', name: 'Honey Pot Count (estimated)', unit: 'count', frequency: 'monthly', required: true },
        { id: 'colony-health', name: 'Colony Health Score (1–5)', unit: 'ratio', frequency: 'monthly', required: true },
        { id: 'brood-area', name: 'Brood Area (frames/cells)', unit: 'count', frequency: 'monthly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['honey-harvest', 'colony-split'],
    },
    {
      id: 'honey-harvest',
      name: 'Honey Harvest',
      typicalDurationDays: 3,
      color: '#d97706',
      inputs: [
        { id: 'tubes', label: 'Sterile Tubes / Jars for Honey', unit: 'count', required: true },
        { id: 'syringe', label: 'Syringe or Tube for Honey Extraction', unit: 'count', required: true },
      ],
      activities: [
        'Harvest only when honey pots are sealed/full',
        'Use sterile syringe to extract from honey storage pots',
        'Do NOT squeeze cerumen — compromises hive structure',
        'Take max 30–40% of honey stores',
        'Never harvest during dearth season',
        'Filter honey through fine mesh (not heated)',
        'Bottle immediately — stingless honey ferments faster than honeybee honey',
        'Refrigerate fresh honey; shelf life 3–12 months refrigerated',
      ],
      measurements: [
        { id: 'honey-litres', name: 'Honey Harvested', unit: 'litre', frequency: 'per_event', required: true },
        { id: 'moisture-stl', name: 'Honey Moisture %', unit: 'percent', frequency: 'per_event', required: true, benchmark: { max: 30 } },
        { id: 'ph', name: 'Honey pH', unit: 'ratio', frequency: 'per_event', required: false, benchmark: { min: 3, max: 4 } },
      ],
      outputs: [
        { id: 'stingless-honey', label: 'Stingless Bee Honey', unit: 'litre', routingOptions: ['sale', 'inventory', 'processing'] },
        { id: 'cerumen', label: 'Cerumen (propolis-wax)', unit: 'g', routingOptions: ['sale', 'processing'] },
      ],
      possibleNextStages: ['colony-management'],
    },
    {
      id: 'colony-split',
      name: 'Colony Division (Multiplication)',
      typicalDurationDays: 90,
      color: '#92400e',
      inputs: [
        { id: 'new-box', label: 'New Colony Box', unit: 'count', required: true },
      ],
      activities: [
        'Divide colony when population is very strong (all frames covered)',
        'Move original box to new location — bees re-orient',
        'Place new box at original position (contains field bees)',
        'Both halves need queen: leave queen cells or introduce mated queen',
        'Leave 60–90 days before harvesting from new colony',
      ],
      measurements: [
        { id: 'daughter-viability', name: 'New Colony Established (Y/N)', unit: 'count', frequency: 'per_event', required: true },
        { id: 'split-date', name: 'Days to First Daughter Harvest', unit: 'day', frequency: 'per_event', required: false },
      ],
      outputs: [
        { id: 'daughter-colony', label: 'Daughter Colony', unit: 'count', routingOptions: ['sale', 'transfer'] },
      ],
      possibleNextStages: ['colony-management'],
    },
  ],
};
