// ─────────────────────────────────────────────────────────────────────────────
// Livestock Extra 2 — Specialised Terrestrial Animals
// Maps to Universal Template T6 — Terrestrial Animal
// Covers: Deer/Venison, Camelids (Alpaca, Llama, Camel)
// ─────────────────────────────────────────────────────────────────────────────
import type { ProductionTemplate } from '../types';

// ─── DEER FARMING (VENISON) ───────────────────────────────────────────────────
export const deerTemplate: ProductionTemplate = {
  id: 'deer-venison',
  name: 'Deer Farming (Venison)',
  shortName: 'Deer',
  category: 'livestock',
  species: 'Cervus elaphus (Red Deer) / Dama dama (Fallow Deer)',
  breed: 'Red Deer / Fallow Deer',
  purpose: 'Venison Meat, Velvet Antler & Trophy',
  description:
    'Semi-intensive deer farming for premium venison meat, velvet antler (velvet for medicine), and trophy/breeding stock sales.',
  icon: '🦌',
  color: '#92400e',
  tags: ['deer', 'venison', 'velvet', 'antler', 'red deer', 'fallow deer', 'game'],
  materials: [
    { id: 'hinds', name: 'Breeding Hinds (females)', unit: 'head', category: 'input' },
    { id: 'stag', name: 'Breeding Stag (male)', unit: 'head', category: 'input' },
    { id: 'deer-feed', name: 'Pasture / Supplement Feed', unit: 'kg', category: 'input' },
    { id: 'velvet', name: 'Velvet Antler (fresh)', unit: 'kg', category: 'output' },
    { id: 'venison-carcass', name: 'Venison Carcass', unit: 'kg', category: 'output' },
    { id: 'venison-retail', name: 'Retail Venison Cuts', unit: 'kg', category: 'output' },
    { id: 'breeding-stock', name: 'Breeding / Trophy Stock (live)', unit: 'head', category: 'output' },
    { id: 'hide', name: 'Deer Hide', unit: 'count', category: 'output' },
  ],
  kpis: [
    { id: 'fawning-rate', name: 'Fawning Rate (fawns/hind/year)', unit: 'ratio', goodDirection: 'up', benchmark: 0.9 },
    { id: 'velvet-yield', name: 'Velvet Yield per Stag per Year', unit: 'kg', goodDirection: 'up', benchmark: 4 },
    { id: 'adg', name: 'Average Daily Gain (Weaner→Slaughter)', unit: 'g', goodDirection: 'up', benchmark: 220 },
    { id: 'carcass-weight', name: 'Average Carcass Weight', unit: 'kg', goodDirection: 'up', benchmark: 70 },
    { id: 'mortality', name: 'Annual Mortality Rate', unit: 'percent', goodDirection: 'down', benchmark: 3 },
  ],
  stages: [
    {
      id: 'breeding',
      name: 'Rut & Breeding (Autumn)',
      typicalDurationDays: 45,
      color: '#fef3c7',
      inputs: [
        { id: 'stag-in', label: 'Breeding Stag (introduce to hinds)', unit: 'head', required: true },
      ],
      activities: [
        'Introduce stag to hind mob at ratio 1:25–30 hinds',
        'Mark hinds with raddle to detect mating',
        'Observe rut behaviour daily — stag should be active',
        'Remove stag after 6 weeks to control fawning date',
        'Monitor body condition of hinds going into rut',
        'Provide extra supplement if hinds are thin (BCS <3)',
      ],
      measurements: [
        { id: 'hinds-mated', name: 'Hinds Marked as Mated', unit: 'count', frequency: 'weekly', required: true },
        { id: 'bcs-hind', name: 'Hind Body Condition Score (1–5)', unit: 'ratio', frequency: 'weekly', required: true, benchmark: { min: 3, max: 4 } },
        { id: 'stag-activity', name: 'Stag Activity Score (1–5)', unit: 'ratio', frequency: 'daily', required: false },
      ],
      outputs: [],
      possibleNextStages: ['pregnancy'],
    },
    {
      id: 'pregnancy',
      name: 'Pregnancy (230–236 Days)',
      typicalDurationDays: 233,
      color: '#e0f2fe',
      inputs: [
        { id: 'pasture', label: 'Pasture / Silage', unit: 'kg', required: true },
        { id: 'mineral', label: 'Mineral Lick / Supplement', unit: 'kg', required: false },
      ],
      activities: [
        'Separate pregnant hinds from stag 6 weeks after mating',
        'Pregnancy scan at 60–90 days to confirm',
        'Manage pasture quality — aim for 5–6 cm pasture height in last trimester',
        'Supplement with hay/silage in winter if pasture inadequate',
        'Provide selenium, cobalt, iodine minerals pre-fawning',
        'Prepare quiet fawning paddocks — minimal disturbance',
      ],
      measurements: [
        { id: 'preg-rate', name: 'Pregnancy Rate (scan)', unit: 'percent', frequency: 'per_event', required: true, benchmark: { target: 90 } },
        { id: 'bcs-preg', name: 'Body Condition Score', unit: 'ratio', frequency: 'monthly', required: true, benchmark: { min: 3, max: 4 } },
        { id: 'pasture-height', name: 'Pasture Height (cm)', unit: 'ratio', frequency: 'weekly', required: false, benchmark: { min: 5, max: 8 } },
      ],
      outputs: [],
      possibleNextStages: ['fawning'],
    },
    {
      id: 'fawning',
      name: 'Fawning & Early Life',
      typicalDurationDays: 60,
      color: '#dbeafe',
      inputs: [],
      activities: [
        'Observe hinds daily from 1 week pre-fawning',
        'Assist dystocia cases promptly — call vet if > 1h labour',
        'Tag fawns (ear tag) within 24h of birth',
        'Weigh fawns at birth — target >5 kg',
        'Check navel — apply iodine tincture to prevent infection',
        'Ensure fawn suckles within 2h',
        'Record dam-fawn pairs',
      ],
      measurements: [
        { id: 'fawning-rate', name: 'Fawning Rate (fawns/hind)', unit: 'ratio', frequency: 'per_event', required: true, benchmark: { target: 0.9 } },
        { id: 'birth-weight', name: 'Average Fawn Birth Weight', unit: 'kg', frequency: 'per_event', required: true, benchmark: { min: 5 } },
        { id: 'fawn-mortality', name: 'Pre-weaning Fawn Mortality %', unit: 'percent', frequency: 'per_event', required: true, benchmark: { max: 5 } },
      ],
      outputs: [],
      possibleNextStages: ['grow-out-deer'],
    },
    {
      id: 'grow-out-deer',
      name: 'Weaning & Venison Grow-Out',
      typicalDurationDays: 365,
      color: '#a3e635',
      inputs: [
        { id: 'pasture-go', label: 'Pasture / Hay / Supplement', unit: 'kg', required: true },
        { id: 'health-go', label: 'Health Programme (vaccines, drenches)', unit: 'count', required: true },
      ],
      activities: [
        'Wean at 12–16 weeks (body weight >35 kg)',
        'Separate weaners from hinds — keep quiet for 3 days post-wean',
        'Drench for parasites (barber pole worm risk)',
        'Vaccinate against clostridial diseases (5-in-1)',
        'Manage pasture rotation — target 6–8 cm height',
        'Weigh monthly to assess growth rate',
        'Cull poor-growing animals or health-problem animals early',
        'Deantler velveting if velvet market is target (Year 2 stags)',
      ],
      measurements: [
        { id: 'live-weight', name: 'Average Live Weight', unit: 'kg', frequency: 'monthly', required: true, benchmark: { target: 100 } },
        { id: 'adg', name: 'Average Daily Gain (g/day)', unit: 'g', frequency: 'monthly', required: true, benchmark: { min: 200, max: 300 } },
        { id: 'worm-count', name: 'Faecal Egg Count', unit: 'count', frequency: 'monthly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['slaughter-deer'],
    },
    {
      id: 'slaughter-deer',
      name: 'Velvet Harvest / Slaughter',
      typicalDurationDays: 14,
      color: '#65a30d',
      inputs: [],
      activities: [
        'Velvet cut at 55–70 days growth (before calcification)',
        'Freeze or dry-process velvet immediately',
        'Slaughter venison at 200–280 kg live weight (13–18 months)',
        'Withhold feed 24h pre-slaughter',
        'Transport to licensed abattoir or on-farm kill if approved',
        'Record carcass weight and dress-out percentage',
        'Grade and cut retail venison — vacuum-pack for premium market',
      ],
      measurements: [
        { id: 'velvet-kg', name: 'Velvet Harvested per Stag', unit: 'kg', frequency: 'per_event', required: false },
        { id: 'slaughter-weight', name: 'Slaughter Live Weight', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'carcass-wt', name: 'Carcass Weight', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'dress-pct', name: 'Dressing Percentage', unit: 'percent', frequency: 'per_event', required: true, benchmark: { target: 52 } },
      ],
      outputs: [
        { id: 'velvet', label: 'Velvet Antler (fresh kg)', unit: 'kg', routingOptions: ['sale', 'inventory'] },
        { id: 'venison-carcass', label: 'Venison Carcass', unit: 'kg', routingOptions: ['sale', 'processing', 'inventory'] },
        { id: 'venison-retail', label: 'Retail Venison Cuts', unit: 'kg', routingOptions: ['sale', 'inventory'] },
        { id: 'hide', label: 'Deer Hide', unit: 'count', routingOptions: ['sale', 'own_use'] },
        { id: 'breeding-stock', label: 'Breeding / Trophy Deer (live)', unit: 'head', routingOptions: ['sale', 'transfer'] },
      ],
      possibleNextStages: ['breeding'],
    },
  ],
};

// ─── ALPACA / LLAMA (CAMELID) ─────────────────────────────────────────────────
export const camelidTemplate: ProductionTemplate = {
  id: 'camelid-fiber',
  name: 'Alpaca / Llama / Camel',
  shortName: 'Camelid',
  category: 'livestock',
  species: 'Vicugna pacos (Alpaca) / Lama glama (Llama) / Camelus dromedarius (Camel)',
  breed: 'Alpaca / Llama / Camel (configurable)',
  purpose: 'Fiber, Meat, Milk & Pack Animal',
  description:
    'Camelid production for premium fiber (alpaca), milk, meat, or pack animal services. Adaptable to arid and high-altitude environments.',
  icon: '🦙',
  color: '#d97706',
  tags: ['alpaca', 'llama', 'camel', 'camelid', 'fiber', 'fleece', 'milk', 'pack animal'],
  materials: [
    { id: 'breeding-females', name: 'Breeding Females', unit: 'head', category: 'input' },
    { id: 'male-stud', name: 'Stud Male', unit: 'head', category: 'input' },
    { id: 'camelid-feed', name: 'Pasture / Hay / Browse', unit: 'kg', category: 'input' },
    { id: 'alpaca-fleece', name: 'Raw Fleece (fiber)', unit: 'kg', category: 'output' },
    { id: 'camelid-meat', name: 'Meat / Carcass', unit: 'kg', category: 'output' },
    { id: 'camel-milk', name: 'Camel Milk', unit: 'litre', category: 'output' },
    { id: 'breeding-animal', name: 'Breeding / Show Animal (live sale)', unit: 'head', category: 'output' },
    { id: 'dung-fuel', name: 'Dung (fuel / fertiliser)', unit: 'kg', category: 'output' },
  ],
  kpis: [
    { id: 'fleece-yield', name: 'Annual Fleece Weight per Animal', unit: 'kg', goodDirection: 'up', benchmark: 3.5 },
    { id: 'fibre-micron', name: 'Mean Fibre Diameter (micron)', unit: 'ratio', goodDirection: 'down', benchmark: 22 },
    { id: 'birth-rate', name: 'Cria (young) Birth Rate', unit: 'percent', goodDirection: 'up', benchmark: 80 },
    { id: 'mortality', name: 'Annual Adult Mortality', unit: 'percent', goodDirection: 'down', benchmark: 3 },
    { id: 'milk-yield', name: 'Camel Daily Milk Yield (if milking)', unit: 'litre', goodDirection: 'up', benchmark: 6 },
  ],
  stages: [
    {
      id: 'mating',
      name: 'Mating & Pregnancy',
      typicalDurationDays: 345,
      color: '#fef3c7',
      inputs: [
        { id: 'male', label: 'Stud Male / Sire', unit: 'head', required: true },
        { id: 'pasture-mate', label: 'Pasture / Supplement', unit: 'kg', required: true },
      ],
      activities: [
        'Introduce male to females at controlled ratio (1:5–10)',
        'Camelids are induced ovulators — multiple matings over 2–3 days',
        'Pregnancy test by ultrasound at 21 days and 45 days',
        'Gestation: Alpaca/Llama ~340 days, Camel ~390 days',
        'Supplement pregnant females in last trimester',
        'Shear alpacas at 30–60 days before birthing date',
      ],
      measurements: [
        { id: 'pregnancy-rate', name: 'Confirmed Pregnancy Rate', unit: 'percent', frequency: 'per_event', required: true, benchmark: { target: 85 } },
        { id: 'bcs', name: 'Body Condition Score (1–5)', unit: 'ratio', frequency: 'monthly', required: true, benchmark: { min: 3, max: 4 } },
        { id: 'weight', name: 'Live Weight', unit: 'kg', frequency: 'monthly', required: true },
      ],
      outputs: [],
      possibleNextStages: ['birthing'],
    },
    {
      id: 'birthing',
      name: 'Birthing (Cria / Foal)',
      typicalDurationDays: 60,
      color: '#fde68a',
      inputs: [],
      activities: [
        'Observe closely around due date (morning births common)',
        'Normal birth: standing in 1h, suckling in 2h',
        'Assist if needed — call vet if >1h active labour',
        'Weigh cria at birth: Alpaca target >6 kg, Llama >10 kg',
        'Apply iodine to navel',
        'Ensure dam-cria bonding within 24h',
        'Record dam, sire, birth date, sex, weight',
      ],
      measurements: [
        { id: 'birth-rate', name: 'Live Birth Rate', unit: 'percent', frequency: 'per_event', required: true },
        { id: 'cria-weight', name: 'Cria Birth Weight', unit: 'kg', frequency: 'per_event', required: true, benchmark: { min: 6 } },
        { id: 'neonatal-mort', name: 'Neonatal Mortality (first 7 days)', unit: 'percent', frequency: 'per_event', required: true, benchmark: { max: 5 } },
      ],
      outputs: [],
      possibleNextStages: ['grow-out-camelid'],
    },
    {
      id: 'grow-out-camelid',
      name: 'Cria Grow-Out & Weaning',
      typicalDurationDays: 180,
      color: '#fcd34d',
      inputs: [
        { id: 'creep', label: 'Creep Feed / Supplementary Pasture', unit: 'kg', required: false },
        { id: 'health-c', label: 'Vaccinations & Drenching', unit: 'count', required: true },
      ],
      activities: [
        'Wean at 6–8 months (30–40 kg)',
        'Monitor parasite levels — drench as needed',
        'Vaccinate CD&T (clostridium + tetanus) at 30 days and 60 days',
        'Halter-train young alpacas early for ease of handling',
        'First shearing at 12 months (Alpaca) — record first-fleece weight',
        'Separate by sex at weaning',
      ],
      measurements: [
        { id: 'growth-wt', name: 'Monthly Liveweight', unit: 'kg', frequency: 'monthly', required: true },
        { id: 'adg-c', name: 'Average Daily Gain', unit: 'g', frequency: 'monthly', required: true, benchmark: { min: 100 } },
        { id: 'fecal', name: 'Faecal Egg Count', unit: 'count', frequency: 'monthly', required: false },
      ],
      outputs: [],
      possibleNextStages: ['fiber-production'],
    },
    {
      id: 'fiber-production',
      name: 'Annual Shearing & Fiber Harvest',
      typicalDurationDays: 7,
      color: '#f59e0b',
      inputs: [
        { id: 'shears', label: 'Electric Shears / Hand Shears', unit: 'count', required: true },
        { id: 'skirting-table', label: 'Skirting Table / Bags', unit: 'count', required: true },
      ],
      activities: [
        'Shear once per year (spring) — when night temperatures >5°C consistently',
        'Restrain animal safely (halter + sit or lay position)',
        'Shear blanket (prime fleece) first, then belly, neck, legs',
        'Skirt fleece on table — remove dung, stain, coarse edges',
        'Sort by colour and grade (fine/medium/coarse)',
        'Weigh, label, and bag each fleece',
        'Test sample for mean fibre diameter (micron) if premium market',
        'Clean up animal after shearing — check teeth, toenails, body condition',
      ],
      measurements: [
        { id: 'fleece-wt', name: 'Fleece Weight per Animal', unit: 'kg', frequency: 'per_event', required: true, benchmark: { target: 3.5 } },
        { id: 'micron', name: 'Mean Fibre Diameter (micron)', unit: 'ratio', frequency: 'per_event', required: true, benchmark: { max: 25 } },
        { id: 'staple-len', name: 'Staple Length (cm)', unit: 'ratio', frequency: 'per_event', required: false, benchmark: { min: 8 } },
        { id: 'colour-grade', name: 'White / Natural / Coloured Split (%)', unit: 'percent', frequency: 'per_event', required: false },
      ],
      outputs: [
        { id: 'alpaca-fleece', label: 'Raw Fleece (fiber)', unit: 'kg', routingOptions: ['sale', 'processing', 'inventory'] },
        { id: 'camelid-meat', label: 'Culled Animal Meat', unit: 'kg', routingOptions: ['sale', 'own_use'] },
        { id: 'breeding-animal', label: 'Breeding / Show Animal', unit: 'head', routingOptions: ['sale', 'transfer'] },
        { id: 'dung-fuel', label: 'Dung Fuel / Fertiliser', unit: 'kg', routingOptions: ['own_use', 'sale'] },
      ],
      possibleNextStages: ['mating'],
    },
  ],
};
