// ─────────────────────────────────────────────────────────────────────────────
// Mushroom Cultivation Templates: Oyster, Button, Shiitake
// ─────────────────────────────────────────────────────────────────────────────
import type { ProductionTemplate } from '../types';

// ─── OYSTER MUSHROOM ─────────────────────────────────────────────────────────
export const oysterMushroomTemplate: ProductionTemplate = {
  id: 'oyster-mushroom',
  name: 'Oyster Mushroom (Pleurotus ostreatus)',
  shortName: 'Oyster Mushroom',
  category: 'mushroom',
  species: 'Oyster Mushroom',
  purpose: 'Edible Mushroom Production',
  description: 'Indoor / controlled oyster mushroom production on straw or sawdust substrate. 45–60 days per cycle.',
  icon: '🍄',
  color: '#a3a3a3',
  tags: ['mushroom', 'oyster', 'pleurotus', 'indoor', 'substrate'],
  materials: [
    { id: 'straw-substrate', name: 'Wheat / Rice Straw (dry)', unit: 'kg', category: 'input' },
    { id: 'oyster-spawn', name: 'Oyster Mushroom Grain Spawn', unit: 'kg', category: 'input' },
    { id: 'pp-bags', name: 'Polypropylene Bags (1.5 kg capacity)', unit: 'count', category: 'input' },
    { id: 'lime', name: 'Agricultural Lime (pH adjustment)', unit: 'kg', category: 'input' },
    { id: 'bran', name: 'Wheat Bran (supplement)', unit: 'kg', category: 'input' },
    { id: 'oyster-fresh', name: 'Fresh Oyster Mushroom', unit: 'kg', category: 'output' },
    { id: 'spent-substrate', name: 'Spent Substrate (compost)', unit: 'kg', category: 'byproduct' },
  ],
  kpis: [
    { id: 'be', name: 'Biological Efficiency (BE)', unit: 'percent', benchmark: 90 },
    { id: 'yield-bag', name: 'Yield / kg Substrate', unit: 'kg', benchmark: 0.7 },
    { id: 'flushes', name: 'Flushes per Bag', unit: 'count', benchmark: 3 },
    { id: 'cycle-days', name: 'Days per Cycle', unit: 'day', benchmark: 50 },
  ],
  stages: [
    {
      id: 'substrate-prep',
      name: 'Substrate Preparation',
      order: 1,
      durationDays: 3,
      color: '#fbbf24',
      inputs: [
        { id: 'straw', label: 'Dry Straw', unit: 'kg', required: true },
        { id: 'lime', label: 'Lime (1–2% of dry weight)', unit: 'kg', required: true },
        { id: 'bran', label: 'Wheat Bran (10–15% of dry weight)', unit: 'kg', required: false },
        { id: 'bags', label: 'PP Bags', unit: 'count', required: true },
      ],
      activities: [
        { id: 'chop', name: 'Chop straw to 3–5 cm pieces', frequency: 'once' },
        { id: 'soak', name: 'Soak straw in lime water (pH 12) for 12–18h', frequency: 'once' },
        { id: 'drain', name: 'Drain to 60–70% moisture content', frequency: 'once' },
        { id: 'pasteurize', name: 'Steam pasteurise at 80°C for 1–2h (or pressure cook)', frequency: 'once' },
        { id: 'cool', name: 'Cool to room temperature before inoculation', frequency: 'once' },
      ],
      measurements: [
        { id: 'dry-weight', name: 'Dry Substrate Weight', unit: 'kg', frequency: 'once', required: true, benchmark: null },
        { id: 'moisture-final', name: 'Final Moisture % (squeeze test)', unit: 'percent', frequency: 'once', required: true, benchmark: 65 },
        { id: 'bags-prepared', name: 'Bags Prepared', unit: 'count', frequency: 'once', required: true, benchmark: null },
      ],
      outputs: [],
      possibleNextStages: ['inoculation'],
      alerts: ['Pasteurise within 24h of hydrating — fermentation begins quickly', 'Cool completely before inoculation — heat kills spawn'],
    },
    {
      id: 'inoculation',
      name: 'Inoculation',
      order: 2,
      durationDays: 1,
      color: '#818cf8',
      inputs: [
        { id: 'spawn', label: 'Grain Spawn', unit: 'kg', required: true },
      ],
      activities: [
        { id: 'sanitize', name: 'Sanitize hands, tools, and workspace with 70% alcohol', frequency: 'once' },
        { id: 'layer', name: 'Layer: substrate → spawn (10% of substrate weight) → substrate → spawn', frequency: 'once' },
        { id: 'seal', name: 'Seal bags, make ventilation holes, label', frequency: 'once' },
        { id: 'move-incub', name: 'Move to incubation room (25°C, dark, no wind)', frequency: 'once' },
      ],
      measurements: [
        { id: 'bags-inocu', name: 'Bags Inoculated', unit: 'count', frequency: 'once', required: true, benchmark: null },
        { id: 'spawn-rate', name: 'Spawn Rate Used', unit: 'percent', frequency: 'once', required: true, benchmark: 10 },
        { id: 'room-temp', name: 'Incubation Room Temp', unit: 'celsius', frequency: 'once', required: true, benchmark: 25 },
      ],
      outputs: [],
      possibleNextStages: ['colonisation'],
      alerts: ['STERILITY is critical — contamination kills the batch', 'Spawn at 10% of dry substrate weight for optimal colonisation speed'],
    },
    {
      id: 'colonisation',
      name: 'Incubation / Colonisation',
      order: 3,
      durationDays: 18,
      color: '#a3e635',
      inputs: [],
      activities: [
        { id: 'temp-check', name: 'Monitor temperature (25°C target)', frequency: 'daily' },
        { id: 'inspect', name: 'Inspect for contamination (green/black moulds = Trichoderma/Aspergillus)', frequency: 'daily' },
        { id: 'remove-contam', name: 'Remove contaminated bags immediately', frequency: 'daily' },
      ],
      measurements: [
        { id: 'colonisation-pct', name: 'Colonisation Progress', unit: 'percent', frequency: 'every_3_days', required: true, benchmark: 50 },
        { id: 'contamination-bags', name: 'Contaminated Bags', unit: 'count', frequency: 'daily', required: true, benchmark: 0 },
        { id: 'room-temp', name: 'Room Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: 25 },
      ],
      outputs: [],
      possibleNextStages: ['fruiting'],
      alerts: ['Full colonisation in 14–21 days — mycelium should be white throughout', 'Green mould (Trichoderma) = discard bag immediately outside growing area'],
    },
    {
      id: 'fruiting',
      name: 'Fruiting Body Development',
      order: 4,
      durationDays: 21,
      color: '#22c55e',
      inputs: [],
      activities: [
        { id: 'move-fruiting', name: 'Move to fruiting room: 20°C, 85–95% RH, 12h light/dark', frequency: 'once' },
        { id: 'open-holes', name: 'Open bags or cut X slits for pinning sites', frequency: 'once' },
        { id: 'mist', name: 'Mist bags / room 3–4× daily (keep humid)', frequency: 'daily' },
        { id: 'ventilate', name: 'Ensure CO₂ <1000 ppm — ventilate 4× daily minimum', frequency: 'daily' },
        { id: 'harvest', name: 'Harvest fruiting bodies before caps fully flatten (pins showing)', frequency: 'daily' },
      ],
      measurements: [
        { id: 'humidity', name: 'Room Humidity', unit: 'percent', frequency: 'daily', required: true, benchmark: 90 },
        { id: 'temp-fruiting', name: 'Room Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: 22 },
        { id: 'co2-ppm', name: 'CO₂ Level', unit: 'ratio', frequency: 'daily', required: false, benchmark: 800 },
        { id: 'first-flush', name: 'Days to First Flush', unit: 'day', frequency: 'once', required: false, benchmark: 7 },
        { id: 'flush1-yield', name: '1st Flush Yield (kg)', unit: 'kg', frequency: 'once', required: true, benchmark: null },
      ],
      outputs: [
        { materialTypeId: 'oyster-fresh', quantity: null, unit: 'kg', routing: 'sale', qualityGrade: 'A' },
      ],
      possibleNextStages: ['resting'],
      alerts: ['Harvest when caps are 6–10 cm — before edges flatten and spores drop', 'HIGH CO₂ causes thin, elongated, pale mushrooms — ventilate!'],
    },
    {
      id: 'resting',
      name: 'Rest & Subsequent Flushes',
      order: 5,
      durationDays: 21,
      color: '#f59e0b',
      inputs: [],
      activities: [
        { id: 'rest', name: 'Rest bags 5–7 days between flushes', frequency: 'once' },
        { id: 'rehydrate', name: 'Rehydrate bags by soaking in water 1h', frequency: 'once' },
        { id: 'pick-flush-2', name: 'Harvest 2nd and 3rd flush', frequency: 'daily' },
        { id: 'spent-compost', name: 'Compost spent substrate after 3rd flush', frequency: 'once' },
      ],
      measurements: [
        { id: 'flush2-yield', name: '2nd Flush Yield', unit: 'kg', frequency: 'once', required: true, benchmark: null },
        { id: 'flush3-yield', name: '3rd Flush Yield', unit: 'kg', frequency: 'once', required: false, benchmark: null },
        { id: 'total-yield', name: 'Total Cycle Yield', unit: 'kg', frequency: 'once', required: true, benchmark: null },
        { id: 'be-pct', name: 'Biological Efficiency %', unit: 'percent', frequency: 'once', required: false, benchmark: 90 },
      ],
      outputs: [
        { materialTypeId: 'oyster-fresh', quantity: null, unit: 'kg', routing: 'sale', qualityGrade: 'A' },
        { materialTypeId: 'spent-substrate', quantity: null, unit: 'kg', routing: 'inventory', qualityGrade: 'A' },
      ],
      possibleNextStages: [],
      alerts: ['BE = (fresh mushroom yield / dry substrate weight) × 100. Target >80%', 'Spent substrate is excellent compost / animal feed supplement'],
    },
  ],
};

// ─── BUTTON MUSHROOM ─────────────────────────────────────────────────────────
export const buttonMushroomTemplate: ProductionTemplate = {
  id: 'button-mushroom',
  name: 'Button Mushroom (Agaricus bisporus)',
  shortName: 'Button Mushroom',
  category: 'mushroom',
  species: 'Button Mushroom',
  purpose: 'Edible Mushroom Production',
  description: 'White/brown button mushroom on composted wheat straw manure substrate. 10–12 week cycle.',
  icon: '🍄',
  color: '#d6d3d1',
  tags: ['mushroom', 'button', 'Agaricus', 'white mushroom', 'compost'],
  materials: [
    { id: 'horse-manure', name: 'Horse / Poultry Manure', unit: 'kg', category: 'input' },
    { id: 'wheat-straw-btn', name: 'Wheat Straw', unit: 'kg', category: 'input' },
    { id: 'btn-spawn', name: 'Button Mushroom Grain Spawn', unit: 'kg', category: 'input' },
    { id: 'peat-casing', name: 'Peat / Casing Layer Soil', unit: 'kg', category: 'input' },
    { id: 'button-fresh', name: 'Fresh Button Mushroom', unit: 'kg', category: 'output' },
    { id: 'btn-spent', name: 'Spent Compost', unit: 'kg', category: 'byproduct' },
  ],
  kpis: [
    { id: 'yield-sqm', name: 'Yield / m²', unit: 'kg', benchmark: 20 },
    { id: 'be-btn', name: 'Biological Efficiency', unit: 'percent', benchmark: 40 },
    { id: 'flushes', name: 'Number of Flushes', unit: 'count', benchmark: 5 },
  ],
  stages: [
    {
      id: 'composting',
      name: 'Phase I Composting (Outdoor, 14–18 days)',
      order: 1,
      durationDays: 18,
      color: '#92400e',
      inputs: [
        { id: 'manure', label: 'Horse / Poultry Manure', unit: 'kg', required: true },
        { id: 'straw', label: 'Wheat Straw', unit: 'kg', required: true },
        { id: 'gypsum', label: 'Gypsum (2% of mix)', unit: 'kg', required: true },
      ],
      activities: [
        { id: 'blend', name: 'Blend manure, straw, and gypsum, wet to 75% moisture', frequency: 'once' },
        { id: 'turn-1', name: 'Turn compost at days 4, 8, 12 to aerate', frequency: 'once' },
        { id: 'temp-check', name: 'Monitor compost temperature (60–70°C = good)', frequency: 'daily' },
      ],
      measurements: [
        { id: 'compost-temp', name: 'Compost Temp at Core', unit: 'celsius', frequency: 'daily', required: true, benchmark: 65 },
        { id: 'moisture', name: 'Compost Moisture %', unit: 'percent', frequency: 'every_3_days', required: true, benchmark: 72 },
      ],
      outputs: [],
      possibleNextStages: ['phase2'],
      alerts: ['Temperature must reach 65–75°C to kill pathogens — do not compress pile', 'If temperature too low — add nitrogen (chicken manure or urea)'],
    },
    {
      id: 'phase2',
      name: 'Phase II Pasteurisation (Indoor, 5–7 days)',
      order: 2,
      durationDays: 7,
      color: '#f59e0b',
      inputs: [],
      activities: [
        { id: 'fill-trays', name: 'Fill growing trays / bags 15–20 cm deep', frequency: 'once' },
        { id: 'pasteurise', name: 'Heat room to 60°C for 8h (kills competitors)', frequency: 'once' },
        { id: 'condition', name: 'Condition at 48–52°C for 5 days (selective microflora)', frequency: 'daily' },
        { id: 'cool-28', name: 'Cool to 28°C before spawning', frequency: 'once' },
      ],
      measurements: [
        { id: 'pasteur-temp', name: 'Peak Pasteurisation Temp', unit: 'celsius', frequency: 'once', required: true, benchmark: 60 },
        { id: 'cond-temp', name: 'Conditioning Temp', unit: 'celsius', frequency: 'daily', required: true, benchmark: 50 },
        { id: 'ammonia', name: 'Ammonia Smell Level', unit: 'ratio', frequency: 'daily', required: false, benchmark: 0 },
      ],
      outputs: [],
      possibleNextStages: ['spawn-run'],
      alerts: ['Ammonia smell must be gone before spawning — high NH₃ kills spawn', 'Good compost smells earthy — bad compost smells sour/ammonia'],
    },
    {
      id: 'spawn-run',
      name: 'Spawn Run & Casing',
      order: 3,
      durationDays: 21,
      color: '#a3e635',
      inputs: [
        { id: 'spawn', label: 'Button Mushroom Grain Spawn', unit: 'kg', required: true },
        { id: 'casing', label: 'Peat:Limestone Casing Mix (1:1)', unit: 'kg', required: true },
      ],
      activities: [
        { id: 'mix-spawn', name: 'Mix spawn into compost at 0.7–1% of fresh compost weight', frequency: 'once' },
        { id: 'incubate', name: 'Maintain 28°C, humidity 80–90%, CO₂ <2000 ppm', frequency: 'daily' },
        { id: 'apply-casing', name: 'Apply casing layer 3–4 cm thick when mycelium visible (day 14)', frequency: 'once' },
        { id: 'irrigate-case', name: 'Irrigate casing to field capacity', frequency: 'daily' },
      ],
      measurements: [
        { id: 'spawn-run-pct', name: 'Spawn Run Progress', unit: 'percent', frequency: 'every_3_days', required: true, benchmark: 50 },
        { id: 'case-moisture', name: 'Casing Moisture %', unit: 'percent', frequency: 'daily', required: true, benchmark: 70 },
      ],
      outputs: [],
      possibleNextStages: ['fruiting'],
      alerts: ['Casing layer is essential for button mushrooms — without it, no pinning', 'Water very gently — do not compact casing'],
    },
    {
      id: 'fruiting',
      name: 'Fruiting & Harvest (5+ flushes)',
      order: 4,
      durationDays: 56,
      color: '#22c55e',
      inputs: [],
      activities: [
        { id: 'reduce-co2', name: 'Reduce CO₂ to <1000 ppm to initiate pinning', frequency: 'once' },
        { id: 'cool-to-18', name: 'Cool to 18–20°C for pin formation', frequency: 'once' },
        { id: 'harvest', name: 'Harvest closed caps — twist and pull cleanly', frequency: 'daily' },
        { id: 'remove-stubs', name: 'Remove all stumps and dead pins to prevent disease', frequency: 'daily' },
        { id: 'rest-refill', name: 'Rest 5–7 days between flushes, re-water casing', frequency: 'weekly' },
      ],
      measurements: [
        { id: 'flush-1', name: '1st Flush Yield / m²', unit: 'kg', frequency: 'once', required: true, benchmark: null },
        { id: 'total-yield', name: 'Total Yield / m²', unit: 'kg', frequency: 'once', required: true, benchmark: 20 },
        { id: 'flushes', name: 'Flushes Obtained', unit: 'count', frequency: 'once', required: true, benchmark: 5 },
        { id: 'average-size', name: 'Avg Button Size', unit: 'celsius', frequency: 'weekly', required: false, benchmark: 4 },
      ],
      outputs: [
        { materialTypeId: 'button-fresh', quantity: null, unit: 'kg', routing: 'sale', qualityGrade: 'A' },
        { materialTypeId: 'btn-spent', quantity: null, unit: 'kg', routing: 'inventory', qualityGrade: 'A' },
      ],
      possibleNextStages: [],
      alerts: ['Harvest closed caps — open caps age fast and are downgraded', 'Wet bubble disease (Lecanicillium): remove infected pins, spray dicloran'],
    },
  ],
};
