import { ProductionTemplate } from '../types';

export const broilerTemplate: ProductionTemplate = {
  id: 'broiler_chicken',
  name: 'Broiler Chicken',
  shortName: 'Broiler',
  category: 'poultry',
  species: 'Chicken',
  purpose: 'Meat',
  description: 'Commercial broiler production — batch-based grow-out from day-old chick to harvest.',
  icon: '🐔',
  color: 'amber',
  tags: ['poultry', 'broiler', 'meat', 'batch'],
  materials: [
    { id: 'day_old_chick', name: 'Day-old Chicks', unit: 'count', category: 'input' },
    { id: 'starter_feed', name: 'Starter Feed', unit: 'kg', category: 'input' },
    { id: 'grower_feed', name: 'Grower Feed', unit: 'kg', category: 'input' },
    { id: 'finisher_feed', name: 'Finisher Feed', unit: 'kg', category: 'input' },
    { id: 'vaccine', name: 'Vaccines', unit: 'count', category: 'input' },
    { id: 'live_broiler', name: 'Live Broilers', unit: 'count', category: 'output' },
    { id: 'broiler_mortality', name: 'Mortality', unit: 'count', category: 'waste' },
    { id: 'litter', name: 'Litter / Manure', unit: 'kg', category: 'byproduct' },
  ],
  kpis: [
    { id: 'fcr', name: 'Feed Conversion Ratio', unit: 'ratio', goodDirection: 'down', benchmark: 1.7, description: 'Feed consumed ÷ live weight gained' },
    { id: 'mortality_rate', name: 'Mortality Rate', unit: '%', goodDirection: 'down', benchmark: 3 },
    { id: 'avg_body_weight', name: 'Avg Body Weight', unit: 'kg', goodDirection: 'up', benchmark: 2.2 },
    { id: 'cost_per_kg', name: 'Cost per kg Live Weight', unit: 'ZMW/kg', goodDirection: 'down' },
    { id: 'revenue_per_bird', name: 'Revenue per Bird', unit: 'ZMW', goodDirection: 'up' },
  ],
  stages: [
    {
      id: 'brooder',
      name: 'Brooding',
      description: 'Week 1–2: heat, starter feed, high mortality risk period',
      typicalDurationDays: 14,
      color: 'yellow',
      inputs: [
        { id: 'day_old_chick', label: 'Day-old Chicks', unit: 'count', required: true },
        { id: 'starter_feed', label: 'Starter Feed', unit: 'kg', required: true },
      ],
      activities: ['Place chicks', 'Manage brooder temperature', 'Administer vitamins', 'Monitor water intake'],
      measurements: [
        { id: 'temp', name: 'Brooder Temperature', unit: 'celsius', frequency: 'daily', required: true, benchmark: { min: 30, max: 35 } },
        { id: 'mortality', name: 'Daily Mortality', unit: 'count', frequency: 'daily', required: true },
        { id: 'feed_intake', name: 'Daily Feed Intake', unit: 'kg', frequency: 'daily', required: true },
        { id: 'water_intake', name: 'Daily Water Intake', unit: 'litre', frequency: 'daily', required: false },
      ],
      outputs: [],
      possibleNextStages: ['grower'],
      alerts: [
        { metric: 'mortality', condition: 'above', threshold: 50, message: 'High mortality — check temperature, ventilation and disease.', severity: 'critical' },
        { metric: 'temp', condition: 'below', threshold: 28, message: 'Brooder temperature too low — risk of chilling.', severity: 'warning' },
      ],
    },
    {
      id: 'grower',
      name: 'Grower',
      description: 'Week 3–4: transition to grower feed, rapid weight gain',
      typicalDurationDays: 14,
      color: 'orange',
      inputs: [
        { id: 'grower_feed', label: 'Grower Feed', unit: 'kg', required: true },
      ],
      activities: ['Switch to grower feed', 'Weekly weighing', 'Adjust stocking density', 'Vaccination (ND booster)'],
      measurements: [
        { id: 'avg_weight', name: 'Average Body Weight', unit: 'kg', frequency: 'weekly', required: true, benchmark: { target: 0.9 } },
        { id: 'mortality', name: 'Daily Mortality', unit: 'count', frequency: 'daily', required: true },
        { id: 'feed_intake', name: 'Daily Feed Intake', unit: 'kg', frequency: 'daily', required: true },
        { id: 'water_feed_ratio', name: 'Water:Feed Ratio', unit: 'ratio', frequency: 'daily', required: false, benchmark: { min: 1.8, max: 2.2 } },
      ],
      outputs: [],
      possibleNextStages: ['finisher'],
    },
    {
      id: 'finisher',
      name: 'Finishing',
      description: 'Week 5–6: finisher feed, approaching target weight',
      typicalDurationDays: 14,
      color: 'red',
      inputs: [
        { id: 'finisher_feed', label: 'Finisher Feed', unit: 'kg', required: true },
      ],
      activities: ['Switch to finisher feed', 'Weekly weighing', 'Prepare harvest logistics', 'Feed withdrawal 6–8h before harvest'],
      measurements: [
        { id: 'avg_weight', name: 'Average Body Weight', unit: 'kg', frequency: 'weekly', required: true, benchmark: { target: 2.2 } },
        { id: 'mortality', name: 'Daily Mortality', unit: 'count', frequency: 'daily', required: true },
        { id: 'feed_intake', name: 'Daily Feed Intake', unit: 'kg', frequency: 'daily', required: true },
        { id: 'uniformity', name: 'Flock Uniformity', unit: 'percent', frequency: 'weekly', required: false, benchmark: { min: 80 } },
      ],
      outputs: [
        { id: 'live_broiler', label: 'Live Broilers', unit: 'count', routingOptions: ['sale', 'processing', 'inventory'] },
        { id: 'litter', label: 'Litter/Manure', unit: 'kg', routingOptions: ['sale', 'own_use', 'waste'] },
      ],
      possibleNextStages: ['harvest'],
    },
    {
      id: 'harvest',
      name: 'Harvest / Sale',
      description: 'Catching, weighing, dispatch, and final records',
      typicalDurationDays: 1,
      color: 'green',
      inputs: [],
      activities: ['Feed withdrawal', 'Catching & crating', 'Live weight measurement', 'Loading & dispatch'],
      measurements: [
        { id: 'total_harvested', name: 'Total Birds Harvested', unit: 'count', frequency: 'per_event', required: true },
        { id: 'total_live_weight', name: 'Total Live Weight', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'avg_live_weight', name: 'Average Live Weight', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'sale_price_per_kg', name: 'Sale Price per kg', unit: 'kg', frequency: 'per_event', required: true },
      ],
      outputs: [
        { id: 'live_broiler', label: 'Live Broilers', unit: 'count', routingOptions: ['sale', 'processing'] },
      ],
      possibleNextStages: [],
    },
  ],
};

export const layerTemplate: ProductionTemplate = {
  id: 'layer_chicken',
  name: 'Layer Chicken',
  shortName: 'Layers',
  category: 'poultry',
  species: 'Chicken',
  purpose: 'Eggs',
  description: 'Commercial egg production — pullet rearing through peak lay and beyond.',
  icon: '🥚',
  color: 'yellow',
  tags: ['poultry', 'layer', 'eggs', 'flock'],
  materials: [
    { id: 'day_old_pullet', name: 'Day-old Pullets', unit: 'count', category: 'input' },
    { id: 'chick_feed', name: 'Chick Feed', unit: 'kg', category: 'input' },
    { id: 'grower_feed', name: 'Grower / Developer Feed', unit: 'kg', category: 'input' },
    { id: 'layer_feed', name: 'Layer Feed', unit: 'kg', category: 'input' },
    { id: 'table_egg', name: 'Table Eggs', unit: 'crate', category: 'output', perishable: true },
    { id: 'hatching_egg', name: 'Hatching Eggs', unit: 'count', category: 'output', perishable: true },
    { id: 'spent_hen', name: 'Spent Hens', unit: 'count', category: 'output' },
    { id: 'layer_mortality', name: 'Mortality', unit: 'count', category: 'waste' },
  ],
  kpis: [
    { id: 'hen_day_production', name: 'Hen Day Production', unit: '%', goodDirection: 'up', benchmark: 85 },
    { id: 'eggs_per_hen', name: 'Eggs per Hen Housed', unit: 'count', goodDirection: 'up', benchmark: 290 },
    { id: 'feed_per_egg', name: 'Feed per Egg', unit: 'g', goodDirection: 'down', benchmark: 130 },
    { id: 'mortality_rate', name: 'Mortality Rate', unit: '%', goodDirection: 'down', benchmark: 5 },
    { id: 'egg_revenue', name: 'Monthly Egg Revenue', unit: 'ZMW', goodDirection: 'up' },
  ],
  stages: [
    {
      id: 'chick',
      name: 'Chick (0–8 wks)',
      typicalDurationDays: 56,
      color: 'yellow',
      inputs: [
        { id: 'day_old_pullet', label: 'Day-old Pullets', unit: 'count', required: true },
        { id: 'chick_feed', label: 'Chick Feed', unit: 'kg', required: true },
      ],
      activities: ['Brooding', 'Vaccination (Marek\'s, Newcastle, Gumboro)', 'Beak trimming', 'Lighting programme'],
      measurements: [
        { id: 'mortality', name: 'Daily Mortality', unit: 'count', frequency: 'daily', required: true },
        { id: 'feed_intake', name: 'Daily Feed Intake', unit: 'kg', frequency: 'daily', required: true },
        { id: 'body_weight', name: 'Average Body Weight', unit: 'kg', frequency: 'weekly', required: true },
      ],
      outputs: [],
      possibleNextStages: ['grower'],
    },
    {
      id: 'grower',
      name: 'Grower / Developer (8–18 wks)',
      typicalDurationDays: 70,
      color: 'orange',
      inputs: [
        { id: 'grower_feed', label: 'Grower Feed', unit: 'kg', required: true },
      ],
      activities: ['Transition to grower feed', 'Uniform feeding', 'Light management', 'Body weight checks'],
      measurements: [
        { id: 'mortality', name: 'Daily Mortality', unit: 'count', frequency: 'daily', required: true },
        { id: 'body_weight', name: 'Average Body Weight', unit: 'kg', frequency: 'weekly', required: true, benchmark: { target: 1.4 } },
        { id: 'uniformity', name: 'Flock Uniformity', unit: 'percent', frequency: 'weekly', required: false, benchmark: { min: 80 } },
      ],
      outputs: [],
      possibleNextStages: ['point_of_lay'],
    },
    {
      id: 'point_of_lay',
      name: 'Point of Lay (18–22 wks)',
      typicalDurationDays: 28,
      color: 'amber',
      inputs: [
        { id: 'layer_feed', label: 'Pre-lay / Layer Feed', unit: 'kg', required: true },
      ],
      activities: ['Transfer to lay house', 'Switch to pre-lay feed', 'Stimulate lighting to 16hrs', 'Nest box preparation'],
      measurements: [
        { id: 'mortality', name: 'Daily Mortality', unit: 'count', frequency: 'daily', required: true },
        { id: 'first_egg_pct', name: 'First Egg %', unit: 'percent', frequency: 'daily', required: true },
      ],
      outputs: [],
      possibleNextStages: ['peak_production'],
    },
    {
      id: 'peak_production',
      name: 'Peak Production (22–40 wks)',
      typicalDurationDays: 126,
      color: 'green',
      inputs: [
        { id: 'layer_feed', label: 'Layer Feed', unit: 'kg', required: true },
      ],
      activities: ['Collect eggs twice daily', 'Grade and pack eggs', 'Daily mortality check', 'Feed and water management'],
      measurements: [
        { id: 'eggs_collected', name: 'Eggs Collected', unit: 'count', frequency: 'daily', required: true },
        { id: 'broken_eggs', name: 'Broken / Cracked Eggs', unit: 'count', frequency: 'daily', required: true },
        { id: 'mortality', name: 'Daily Mortality', unit: 'count', frequency: 'daily', required: true },
        { id: 'feed_intake', name: 'Daily Feed Intake', unit: 'kg', frequency: 'daily', required: true },
        { id: 'hen_day_pct', name: 'Hen Day Production %', unit: 'percent', frequency: 'daily', required: false },
      ],
      outputs: [
        { id: 'table_egg', label: 'Table Eggs', unit: 'crate', routingOptions: ['sale', 'inventory', 'processing'] },
        { id: 'hatching_egg', label: 'Hatching Eggs', unit: 'count', routingOptions: ['incubation', 'sale'] },
      ],
      possibleNextStages: ['late_lay'],
    },
    {
      id: 'late_lay',
      name: 'Late Lay & Depletion (40–72 wks)',
      typicalDurationDays: 224,
      color: 'slate',
      inputs: [
        { id: 'layer_feed', label: 'Layer Feed', unit: 'kg', required: true },
      ],
      activities: ['Monitor production decline', 'Consider moulting decision', 'Plan depletion date', 'Collect and sell spent hens'],
      measurements: [
        { id: 'eggs_collected', name: 'Eggs Collected', unit: 'count', frequency: 'daily', required: true },
        { id: 'mortality', name: 'Daily Mortality', unit: 'count', frequency: 'daily', required: true },
        { id: 'hen_day_pct', name: 'Hen Day Production %', unit: 'percent', frequency: 'daily', required: true },
      ],
      outputs: [
        { id: 'table_egg', label: 'Table Eggs', unit: 'crate', routingOptions: ['sale', 'inventory', 'processing'] },
        { id: 'spent_hen', label: 'Spent Hens', unit: 'count', routingOptions: ['sale', 'processing', 'own_use'] },
      ],
      possibleNextStages: [],
    },
  ],
};

export const broilerBreederTemplate: ProductionTemplate = {
  id: 'broiler_breeder',
  name: 'Broiler Breeder',
  shortName: 'Breeders',
  category: 'poultry',
  species: 'Chicken',
  purpose: 'Breeding',
  description: 'Breeding flock producing hatching eggs for broiler hatchery.',
  icon: '🥚',
  color: 'rose',
  tags: ['poultry', 'breeder', 'hatching-eggs', 'hatchery'],
  materials: [
    { id: 'pullet', name: 'Pullets (Breeders)', unit: 'count', category: 'input' },
    { id: 'cockerel', name: 'Cockerels', unit: 'count', category: 'input' },
    { id: 'breeder_feed', name: 'Breeder Feed', unit: 'kg', category: 'input' },
    { id: 'hatching_egg', name: 'Hatching Eggs', unit: 'count', category: 'output', perishable: true },
    { id: 'table_egg', name: 'Table Eggs (rejects)', unit: 'count', category: 'output', perishable: true },
  ],
  kpis: [
    { id: 'hatchability', name: 'Hatchability', unit: '%', goodDirection: 'up', benchmark: 85 },
    { id: 'fertile_egg_pct', name: 'Fertile Egg %', unit: '%', goodDirection: 'up', benchmark: 92 },
    { id: 'hatching_eggs_per_hen', name: 'Hatching Eggs / Hen', unit: 'count', goodDirection: 'up' },
  ],
  stages: [
    {
      id: 'production',
      name: 'Egg Production',
      typicalDurationDays: 280,
      color: 'rose',
      inputs: [
        { id: 'breeder_feed', label: 'Breeder Feed', unit: 'kg', required: true },
      ],
      activities: ['Collect hatching eggs daily', 'Grade and store eggs', 'Monitor cockerel ratio', 'Fertility checks'],
      measurements: [
        { id: 'eggs_collected', name: 'Eggs Collected', unit: 'count', frequency: 'daily', required: true },
        { id: 'hatching_eggs', name: 'Hatching Eggs Selected', unit: 'count', frequency: 'daily', required: true },
        { id: 'mortality', name: 'Daily Mortality', unit: 'count', frequency: 'daily', required: true },
      ],
      outputs: [
        { id: 'hatching_egg', label: 'Hatching Eggs', unit: 'count', routingOptions: ['incubation', 'sale'] },
        { id: 'table_egg', label: 'Table Eggs (rejects)', unit: 'count', routingOptions: ['sale', 'processing'] },
      ],
      possibleNextStages: [],
    },
  ],
};
