import { ProductionTemplate } from '../types';

export const maizeMealTemplate: ProductionTemplate = {
  id: 'maize_milling',
  name: 'Maize Milling',
  shortName: 'Milling',
  category: 'processing',
  description: 'Maize grain → mealie meal, bran, and grits. Track yield, cost per bag, and stock.',
  icon: '🏭',
  color: 'stone',
  tags: ['processing', 'milling', 'maize', 'flour'],
  materials: [
    { id: 'maize_grain_in', name: 'Maize Grain (Input)', unit: 'kg', category: 'input' },
    { id: 'mealie_meal_super', name: 'Mealie Meal (Super)', unit: 'kg', category: 'output' },
    { id: 'mealie_meal_roller', name: 'Roller Meal', unit: 'kg', category: 'output' },
    { id: 'bran', name: 'Bran', unit: 'kg', category: 'byproduct' },
    { id: 'grits', name: 'Grits', unit: 'kg', category: 'byproduct' },
    { id: 'milling_waste', name: 'Waste / Dust', unit: 'kg', category: 'waste' },
    { id: '25kg_bag', name: '25kg Bag', unit: 'count', category: 'input' },
    { id: '50kg_bag', name: '50kg Bag', unit: 'count', category: 'input' },
  ],
  kpis: [
    { id: 'extraction_rate', name: 'Meal Extraction Rate', unit: '%', goodDirection: 'up', benchmark: 72, description: 'kg meal per 100kg maize' },
    { id: 'cost_per_50kg', name: 'Cost per 50kg Bag', unit: 'ZMW', goodDirection: 'down' },
    { id: 'bran_yield', name: 'Bran Yield', unit: '%', goodDirection: 'up', benchmark: 18 },
    { id: 'wastage', name: 'Wastage', unit: '%', goodDirection: 'down', benchmark: 5 },
  ],
  stages: [
    {
      id: 'receiving',
      name: 'Grain Receiving & QC',
      typicalDurationDays: 1,
      color: 'amber',
      inputs: [
        { id: 'maize_grain_in', label: 'Maize Grain', unit: 'kg', required: true },
      ],
      activities: ['Weigh incoming grain', 'Moisture test', 'Aflatoxin test', 'Grade assessment', 'Record supplier'],
      measurements: [
        { id: 'gross_weight', name: 'Gross Weight (kg)', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'moisture_pct', name: 'Moisture %', unit: 'percent', frequency: 'per_event', required: true, benchmark: { max: 13.5 } },
        { id: 'aflatoxin_ppb', name: 'Aflatoxin (ppb)', unit: 'ratio', frequency: 'per_event', required: false, benchmark: { max: 10 } },
      ],
      outputs: [],
      possibleNextStages: ['cleaning'],
    },
    {
      id: 'cleaning',
      name: 'Cleaning & Conditioning',
      typicalDurationDays: 1,
      color: 'slate',
      inputs: [],
      activities: ['Pass through cleaner/aspirator', 'Remove stones, cobs, trash', 'Temper with water if needed'],
      measurements: [
        { id: 'clean_weight', name: 'Clean Grain Weight (kg)', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'cleaning_loss_pct', name: 'Cleaning Loss %', unit: 'percent', frequency: 'per_event', required: false },
      ],
      outputs: [],
      possibleNextStages: ['milling'],
    },
    {
      id: 'milling',
      name: 'Milling & Grading',
      typicalDurationDays: 1,
      color: 'stone',
      inputs: [],
      activities: ['Dehull / degerm', 'Mill to required grade', 'Sift and separate', 'Grade into meal / bran / grits'],
      measurements: [
        { id: 'meal_kg', name: 'Meal Output (kg)', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'bran_kg', name: 'Bran Output (kg)', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'grits_kg', name: 'Grits Output (kg)', unit: 'kg', frequency: 'per_event', required: false },
        { id: 'waste_kg', name: 'Waste / Dust (kg)', unit: 'kg', frequency: 'per_event', required: true },
        { id: 'extraction_rate', name: 'Extraction Rate %', unit: 'percent', frequency: 'per_event', required: true },
      ],
      outputs: [
        { id: 'mealie_meal_super', label: 'Mealie Meal (Super)', unit: 'kg', routingOptions: ['inventory', 'sale'] },
        { id: 'mealie_meal_roller', label: 'Roller Meal', unit: 'kg', routingOptions: ['inventory', 'sale'] },
        { id: 'bran', label: 'Bran', unit: 'kg', routingOptions: ['inventory', 'sale', 'own_use'] },
        { id: 'grits', label: 'Grits', unit: 'kg', routingOptions: ['inventory', 'sale'] },
        { id: 'milling_waste', label: 'Waste / Dust', unit: 'kg', routingOptions: ['waste', 'own_use'] },
      ],
      possibleNextStages: ['packaging'],
    },
    {
      id: 'packaging',
      name: 'Packaging & Dispatch',
      typicalDurationDays: 1,
      color: 'green',
      inputs: [
        { id: '25kg_bag', label: '25kg Bags', unit: 'count', required: false },
        { id: '50kg_bag', label: '50kg Bags', unit: 'count', required: false },
      ],
      activities: ['Weigh and fill bags', 'Seal and label', 'Stack in warehouse', 'Record finished goods'],
      measurements: [
        { id: 'bags_25kg', name: 'Bags Packed (25kg)', unit: 'count', frequency: 'per_event', required: false },
        { id: 'bags_50kg', name: 'Bags Packed (50kg)', unit: 'count', frequency: 'per_event', required: false },
        { id: 'cost_per_50kg_bag', name: 'Cost per 50kg Bag (ZMW)', unit: 'kg', frequency: 'per_event', required: false },
      ],
      outputs: [],
      possibleNextStages: [],
    },
  ],
};

export const dairyProcessingTemplate: ProductionTemplate = {
  id: 'dairy_processing',
  name: 'Dairy Processing',
  shortName: 'Dairy',
  category: 'processing',
  description: 'Raw milk → pasteurised milk, yoghurt, cheese, or butter.',
  icon: '🥛',
  color: 'sky',
  tags: ['processing', 'dairy', 'milk', 'yoghurt'],
  materials: [
    { id: 'raw_milk_in', name: 'Raw Milk', unit: 'litre', category: 'input', perishable: true, requiresColdChain: true },
    { id: 'pasteurised_milk', name: 'Pasteurised Milk', unit: 'litre', category: 'output', perishable: true },
    { id: 'yoghurt', name: 'Yoghurt', unit: 'litre', category: 'output', perishable: true },
    { id: 'fresh_cheese', name: 'Fresh Cheese', unit: 'kg', category: 'output', perishable: true },
    { id: 'whey', name: 'Whey', unit: 'litre', category: 'byproduct', perishable: true },
  ],
  kpis: [
    { id: 'pasteurisation_yield', name: 'Pasteurisation Yield', unit: '%', goodDirection: 'up', benchmark: 98 },
    { id: 'yoghurt_yield_per_litre', name: 'Yoghurt Yield per Litre', unit: 'litre', goodDirection: 'up', benchmark: 0.95 },
    { id: 'cost_per_litre', name: 'Cost per Litre Processed', unit: 'ZMW', goodDirection: 'down' },
  ],
  stages: [
    {
      id: 'receiving_milk',
      name: 'Milk Receiving & Testing',
      typicalDurationDays: 1,
      color: 'sky',
      inputs: [
        { id: 'raw_milk_in', label: 'Raw Milk', unit: 'litre', required: true },
      ],
      activities: ['Measure volume', 'Temp check (<4°C)', 'Alcohol/SNF test', 'Reject sub-standard milk'],
      measurements: [
        { id: 'volume_received', name: 'Volume Received (litres)', unit: 'litre', frequency: 'per_event', required: true },
        { id: 'temp_on_arrival', name: 'Temp on Arrival (°C)', unit: 'celsius', frequency: 'per_event', required: true, benchmark: { max: 6 } },
        { id: 'snf', name: 'SNF %', unit: 'percent', frequency: 'per_event', required: false, benchmark: { min: 8.5 } },
        { id: 'fat_pct', name: 'Fat %', unit: 'percent', frequency: 'per_event', required: false, benchmark: { min: 3.5 } },
      ],
      outputs: [],
      possibleNextStages: ['pasteurisation'],
    },
    {
      id: 'pasteurisation',
      name: 'Pasteurisation',
      typicalDurationDays: 1,
      color: 'blue',
      inputs: [],
      activities: ['HTST or batch pasteurisation', 'Cool to <4°C', 'Sample for microbiology'],
      measurements: [
        { id: 'volume_pasteurised', name: 'Volume Pasteurised (litres)', unit: 'litre', frequency: 'per_event', required: true },
        { id: 'pasteurisation_temp', name: 'Pasteurisation Temp (°C)', unit: 'celsius', frequency: 'per_event', required: true, benchmark: { min: 72 } },
        { id: 'hold_time', name: 'Hold Time (seconds)', unit: 'count', frequency: 'per_event', required: false },
      ],
      outputs: [
        { id: 'pasteurised_milk', label: 'Pasteurised Milk', unit: 'litre', routingOptions: ['inventory', 'sale', 'processing'] },
      ],
      possibleNextStages: ['yoghurt_production', 'packaging'],
    },
    {
      id: 'yoghurt_production',
      name: 'Yoghurt Production',
      typicalDurationDays: 1,
      color: 'purple',
      inputs: [],
      activities: ['Heat milk to 43°C', 'Add starter culture', 'Incubate 4–8 hrs', 'Cool and flavour', 'Fill cups/sachets'],
      measurements: [
        { id: 'yoghurt_volume', name: 'Yoghurt Made (litres)', unit: 'litre', frequency: 'per_event', required: true },
        { id: 'acidity', name: 'Final Acidity (pH)', unit: 'ratio', frequency: 'per_event', required: false, benchmark: { max: 4.5 } },
      ],
      outputs: [
        { id: 'yoghurt', label: 'Yoghurt', unit: 'litre', routingOptions: ['inventory', 'sale'] },
        { id: 'whey', label: 'Whey', unit: 'litre', routingOptions: ['sale', 'own_use', 'waste'] },
      ],
      possibleNextStages: [],
    },
    {
      id: 'packaging',
      name: 'Packaging & Cold Store',
      typicalDurationDays: 1,
      color: 'green',
      inputs: [],
      activities: ['Fill sachets / bottles', 'Label and date', 'Load cold store (<4°C)', 'Dispatch orders'],
      measurements: [
        { id: 'units_packed', name: 'Units Packed', unit: 'count', frequency: 'per_event', required: true },
        { id: 'cold_store_temp', name: 'Cold Store Temp (°C)', unit: 'celsius', frequency: 'per_event', required: true, benchmark: { max: 4 } },
      ],
      outputs: [],
      possibleNextStages: [],
    },
  ],
};
